### ISSUE TITLE
Login feature in flipkart clone

### ISSUE THREAD

**Issue by lonlander** [Rayman-Sodhi/Clone-IT#1]
The flipkart clone can be improvised by adding a login page with the login credentials of users stored in a secure database.

**Comment by lonlander** [comment]
I would like to work on this issue

**Comment by Rayman-Sodhi** [comment]
Sure , I will look into the labels and grading system and then assign you .

**Comment by Rayman-Sodhi** [comment]
Hi  @lonlander  you can add your role in the excel sheet and start working on this issue
