### ISSUE TITLE
Creating a Help and FAQ page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Rayman-Sodhi/Clone-IT#101]
It seems the Help & FAQ page is missing.

The link is given in footer.

So I can create one and link it to it.

**Comment by Rayman-Sodhi** [comment]
sure you can work on this . Please  send a  ss before making a pr

**Comment by Kumar-laxmi** [comment]
I think you should assign Level-3 since this would take time

**Comment by Rayman-Sodhi** [comment]
could you explain the complexity of issue.Because all other issues are still level 1 . What are the things you will be doing?

**Comment by Kumar-laxmi** [comment]
No cuz what I have seen till now creating a new page comes under Level-3

**Comment by Kumar-laxmi** [comment]
Ok no problem I have no issue with Level-1

**Comment by Devmindtk** [comment]
I would like to work on  this issue please assign it to mr
