### ISSUE TITLE
Add Disney Plus Clone

### ISSUE THREAD

**Issue by mayank-del** [Rayman-Sodhi/Clone-IT#102]
I want to add Disney front-end clone

**Comment by Rayman-Sodhi** [comment]
is it similar to #48?

**Comment by mayank-del** [comment]
I don't think so

**Comment by gurjeetsinghvirdee** [comment]
> I don't think so

What the difference b/w hotstar and disney plus? Can you explain and if your clone have some extra features then why not update existing hotstar

**Comment by whiteHatpro** [comment]
@mayank-del update?

**Comment by gurjeetsinghvirdee** [comment]
closing this issue coz of no response from contributor side
