### ISSUE TITLE
Clicking the image to open link in new tab 

### ISSUE THREAD

**Issue by Yasshu55** [Rayman-Sodhi/Clone-IT#104]
When a user clicks any of the following social media icons the page opens in the current tab
![pics](https://user-images.githubusercontent.com/95294297/157053601-977cc58a-2bb1-4115-9849-faea8b0f1281.PNG)
I would like to change the code to redirect the page to a new tab, Hope to fix this issue please assign it to me

**Comment by gurjeetsinghvirdee** [comment]
hey @Yasshu55 assigned to you

**Comment by gurjeetsinghvirdee** [comment]
are you in gssoc?

**Comment by Yasshu55** [comment]
Yes @gurjeetsinghvirdee thank you
