### ISSUE TITLE
Startbucks  hompage

### ISSUE THREAD

**Issue by RAHULBAWA777** [Rayman-Sodhi/Clone-IT#105]
startbucks homepages with beautiful styling to be made

**Comment by gurjeetsinghvirdee** [comment]
> startbucks homepages with beautiful styling to be made

Already added if you add extra features to it then I will assign you

**Comment by RAHULBAWA777** [comment]
Ok... I'll let you know 🙂

**Comment by gurjeetsinghvirdee** [comment]
So are you want to work on this issue @RAHULBAWA777

**Comment by gurjeetsinghvirdee** [comment]
Closing this issue coz of no response

**Comment by RAHULBAWA777** [comment]
Working.

**Comment by gurjeetsinghvirdee** [comment]
?
