### ISSUE TITLE
Gmail Clone

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#106]
Hi, I am **TRIDIB BAG.**  I'm a GSSoC22 participant.
I want to  add a clone of the user Interface of **Gmail** using  HTML, CSS, JS. I am really willing to contribute into it.

Can you please assign it to me?

**Comment by Mrjoy832** [comment]
@Rayman-Sodhi  please assign it to me.

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 Add Screenshots or Videos so our PA and mentor will check what you add and how it works

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi @whiteHatpro please add Level label

**Comment by whiteHatpro** [comment]
@Mrjoy832 all the best!!
Happy contributing🚀

**Comment by Mrjoy832** [comment]
> @Mrjoy832 Add Screenshots or Videos so our PA and mentor will check what you add and how it works

Okay
