### ISSUE TITLE
Tesla Landing page 

### ISSUE THREAD

**Issue by ayush-sleeping** [Rayman-Sodhi/Clone-IT#109]
I will make Try my best to make clone of Tesla landing page with the use Html, Css and js , this will help me to increase the skills of my frontend skills.

#

Hey @Rayman-Sodhi ,
I want to work on this issue under @GSSOC'22 ,

**Comment by whiteHatpro** [comment]
@ayush-sleeping all the best!!
happy contributing🚀

**Comment by ayush-sleeping** [comment]
> @ayush-sleeping all the best!!
> happy contributing🚀

Hey maintainer , Because of some urgent Problem, I unable to puch PR .
My project is completed, As soon as I will reach home , I will push PR . ☺️
