### ISSUE TITLE
Adding a testimonial slider section in KFC clone website

### ISSUE THREAD

**Issue by sanjana317** [Rayman-Sodhi/Clone-IT#11]
The website can be enhanced by adding a testimonial slider section for offers and more.

**Comment by Rayman-Sodhi** [comment]
Please complete your previous issue first

**Comment by Rayman-Sodhi** [comment]
offers has been added

**Comment by Rayman-Sodhi** [comment]
can add other sections

**Comment by sanjana317** [comment]
okay thank you

**Comment by sanjana317** [comment]
the offers are not aligned properly. Can I work on that by aligning them and adding a slider?

**Comment by Rayman-Sodhi** [comment]
sure

**Comment by sanjana317** [comment]
thank you
