### ISSUE TITLE
Custom scroll bar

### ISSUE THREAD

**Issue by Pranai2518** [Rayman-Sodhi/Clone-IT#113]
The present scroll bar looks like a basic one.

![1](https://user-images.githubusercontent.com/75829770/157373316-e5e1fc74-f7ab-449d-b9ec-59a2d1e5f2d2.png)

I want to make it a bit look like the below.

![3](https://user-images.githubusercontent.com/75829770/157373780-de66f51f-28ef-449d-8390-3fe9ebefe455.png)

**Comment by gurjeetsinghvirdee** [comment]
There is no difference in both scrollbars in 2nd image it looked like some gradient, if you change more things in the scrollbar to look good then I'll assign you

**Comment by gurjeetsinghvirdee** [comment]
Closing this issue bcoz no response from contributor side
