### ISSUE TITLE
Updating and correcting Readme

### ISSUE THREAD

**Issue by Girlwithasmile** [Rayman-Sodhi/Clone-IT#114]
Hello, this is a contributer at gssoc'22. In the readme section certain clones are not in table format. So I would like to update that.
![Screenshot 2022-03-09 113639](https://user-images.githubusercontent.com/98261167/157384137-4c99102f-a194-483e-8a29-cc814b9c9fab.png)

**Comment by gurjeetsinghvirdee** [comment]
You already did these changes in your Starbucks clone, So I'm closing this issue
