### ISSUE TITLE
Adding missing hover effects in microsoft clone

### ISSUE THREAD

**Issue by Girlwithasmile** [Rayman-Sodhi/Clone-IT#115]
Hello I am a gssoc'22 contributer and I would like to work on this issue. Some hover effects are missing in microsoft clone. Eg-in navbar, buttons, etc.

**Comment by gurjeetsinghvirdee** [comment]
> Hello I am a gssoc'22 contributer and I would like to work on this issue. Some hover effects are missing in microsoft clone. Eg-in navbar, buttons, etc.

Hovers are working fine, and the in the navbar that was a hover style looks like box-shadow but it's working fine, So I'm closing this issue
