### ISSUE TITLE
UI Enhancement of Flipkart-clone

### ISSUE THREAD

**Issue by kalashvasaniya** [Rayman-Sodhi/Clone-IT#118]
UI Enhancement of Flipkart-clone

**Comment by gurjeetsinghvirdee** [comment]
> UI Enhancement of Flipkart-clone

Describe clearly or show ss what you want to change like before after, if it LGTM will assign you

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya update?
> 
> 
> 
> 

Hey you are not assigned to me how will I start working on that?

**Comment by gurjeetsinghvirdee** [comment]
> > @kalashvasaniya update?
> > 
> > 
> > 
> > 
> 
> Hey you are not assigned to me how will I start working on that?

You are assigned @kalashvasaniya start working on you have 6 days to complete this issue

**Comment by priyanshusingh305** [comment]
I would like to work on this issue

**Comment by whiteHatpro** [comment]
> I would like to work on this issue

Kalash is already working on this issue

**Comment by dvlsatya** [comment]
I would like to work on this issue

**Comment by gurjeetsinghvirdee** [comment]
> I would like to work on this issue

Already issued

**Comment by gurjeetsinghvirdee** [comment]
@priyanshusingh305 assigned to u

**Comment by kalashvasaniya** [comment]
@gurjeetsinghvirdee can you pls. assign this to me beacause no one is working on that!

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @kalashvasaniya
