### ISSUE TITLE
Adding text color functionality in GOOGLE KEEP CLONE

### ISSUE THREAD

**Issue by ruchika2210** [Rayman-Sodhi/Clone-IT#119]
By clicking the color functionality , color window will pop up and by selecting the color , text color can be changed.

**Comment by gurjeetsinghvirdee** [comment]
> By clicking the color functionality , color window will pop up and by selecting the color , text color can be changed.

Before making a PR show your changes here

**Comment by gurjeetsinghvirdee** [comment]
@ruchika2210 are you still working on this issue?

**Comment by gurjeetsinghvirdee** [comment]
closing this issue coz of no response from contributor @ruchika2210
