### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#125]
Make proper contributor guidelines use images also so it was better to understand for beginners

**Comment by Pranai2518** [comment]
Can you be more specific on this issue?

**Comment by gurjeetsinghvirdee** [comment]
> Can you be more specific on this issue? What are the changes you are expecting from the current one.

better to add an img that how to clone or fork like that

**Comment by Pranai2518** [comment]
Okay. I would like to work on this issue. Can you assign me.

**Comment by gurjeetsinghvirdee** [comment]
> Okay. I would like to work on this issue. Can you assign me.

sure

**Comment by gurjeetsinghvirdee** [comment]
Send ss before PR
