### ISSUE TITLE
Behance clone

### ISSUE THREAD

**Issue by simplyNour** [Rayman-Sodhi/Clone-IT#132]
Hello, I want to clone this site, GSSOC'22
https://www.behance.net/

**Comment by NourYoussry** [comment]
@gurjeetsinghvirdee can you assign me this issue?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee can you assign me this issue?

Yeah sure go ahead @NourYoussry

**Comment by gurjeetsinghvirdee** [comment]
are you still working on this issue @NourYoussry

**Comment by gurjeetsinghvirdee** [comment]
are me PR bnara tha😒
