### ISSUE TITLE
Add Twitter Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [Rayman-Sodhi/Clone-IT#141]
### Is your feature request related to a problem? Please describe.

Yes, since twitter is one of the most famous social media platforms.

### Describe the solution you'd like.

I will be creating this clone using React JS Framework

### Describe alternatives you've considered.

If not React JS, atleast with Node JS and Bootstrap

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/76027425/158721310-67f2ea85-bcc3-4854-849b-266f5a20e334.png)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to you @Kumar-laxmi
