### ISSUE TITLE
Add Candy Crush Clone

### ISSUE THREAD

**Issue by Adit0507** [Rayman-Sodhi/Clone-IT#142]
### Is your feature request related to a problem? Please describe.

I would like to add a Candy crush clone which works exactly like the original game.

### Describe the solution you'd like.

It can be only played on the PC/ Laptop using mousepad.

Live site: https://adit0507.github.io/Candy-Crush/

## Screenshot
![candy-crush](https://user-images.githubusercontent.com/78037846/158761738-eaac7483-59fb-4b0b-94fe-6f96e20d3482.PNG)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to you @Adit0507 & you are gssoc 22 contributor?
