### ISSUE TITLE
Add some new features in FAQ page

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#150]
Add some new features to the FAQ page like:

- Edit response: make an edit button that function to edit the answers written over there

- Pin the post: like some questions are common and people ask most of the time so we can pin that post, like Github we pin max 3 repos 

Make a pin button so we pin the post or most asked question 

and add the FAQ page menu in Navbar

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi if you want to add some extra feature please add it

**Comment by rachultimate** [comment]
I'd like to work in this issue.

I already cloned the repository, created a fork, commited and: 
-Created an "Ask Question" feature in the FAQ page;
-Added a FAQ page menu in the navbar

But the other features mentioned aren't really clear, could you explain them better?
That's my first time ever working on an issue and contributing to an open-source project, I'm sorry if I made any mistake.

**Comment by gurjeetsinghvirdee** [comment]
> I'd like to work in this issue.
> 
> I already cloned the repository, created a fork, commited and: 
> -Created an "Ask Question" feature in the FAQ page;
> -Added the FAQ page menu in the navbar
> 
> But the other features mentioned aren't really clear, could you explain them better?
> That's my first time ever working on an issue and contributing to an open-source project, I'm sorry if I made any mistake.

Are from GSSOC 22?  coz this issue created for this coding challenge

**Comment by rachultimate** [comment]
Oh, no I'm not, sorry.

**Comment by dude-curious** [comment]
I would like to work on this issue under GSSoC 22. Please assign me this issue.

**Comment by gurjeetsinghvirdee** [comment]
> Oh, no I'm not, sorry.

No, issues

**Comment by gurjeetsinghvirdee** [comment]
Assigning you @dude-curious but you have to complete in 6 days

**Comment by dude-curious** [comment]
Thank you
Will complete it!

**Comment by dude-curious** [comment]
Can I use MongoDB to store the questions? @gurjeetsinghvirdee

**Comment by dude-curious** [comment]
Where should I store the Database?

**Comment by gurjeetsinghvirdee** [comment]
> Where should I store the Database?

Now make your own after some time I will change the connection to the Admins account

**Comment by dude-curious** [comment]
Ok, Thanks

**Comment by dude-curious** [comment]
This is a static website and I need to use NodeJs for storing data, should I need to initialize Node in just the 'FAQ' folder ??

**Comment by gurjeetsinghvirdee** [comment]
> This is a static website and I need to use NodeJs for storing data, should I need to initialize Node in just the 'FAQ' folder ??
> @gurjeetsinghvirdee 

Who stopped you to do this go ahead

**Comment by gurjeetsinghvirdee** [comment]
@Kumar-laxmi don't mention different PR in this issue 
FAQ issue was different and clones issue was different & fix this issues first either I have to remove you in 3 days

**Comment by Kumar-laxmi** [comment]
@gurjeetsinghvirdee  Ohk I am really sorry, but maybe I will work on this issue sometimes later, so please don't assign to me

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee  Ohk I am really sorry, but maybe I will work on this issue sometimes later, so please don't assign to me

Sorry but this was necessary if you can't work i have to pin it open for all

**Comment by MitAbhay** [comment]
@gurjeetsinghvirdee  I want to work on this issue if it is still pending, I am a Gssoc22 contributor.

**Comment by gurjeetsinghvirdee** [comment]
assigned to u @MitAbhay

**Comment by gurjeetsinghvirdee** [comment]
you have a week to complete this @MitAbhay
