### ISSUE TITLE
Title:  Add Unsplash Clone

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Rayman-Sodhi/Clone-IT#152]
### Is your feature request related to a problem? Please describe.

I would to like to contribute this project. 
Tech stack: Html,css,Javascript

### Describe the solution you'd like.

It will be a clone that related to Unsplash photography website.

### Add any other context or screenshots about the feature request here.

![Unsplash Clone](https://user-images.githubusercontent.com/72568715/159135410-b670faa8-71ef-447d-bb77-41198ddc59b1.PNG)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Sulagna-Dutta-Roy
