### ISSUE TITLE
Add Valorant Website Clone

### ISSUE THREAD

**Issue by MonarchGitHub** [Rayman-Sodhi/Clone-IT#153]
### Is your feature request related to a problem? Please describe.

I want to clone the **Valorant website**, the website has lots of cool animations and it will be a good learning resource for upcoming web developers who will explore the code. You can take a look at their website [HERE](https://playvalorant.com/en-us/).

### Describe the solution you'd like.

_Here are some screenshots of the website-_

![image](https://user-images.githubusercontent.com/74449136/159151750-bb843d0b-7a2c-4674-91c3-c2f150c91c67.png)
***************************
![image](https://user-images.githubusercontent.com/74449136/159151769-8b8ce1cb-22de-4931-a008-6a9ccaf010de.png)

**Comment by MonarchGitHub** [comment]
Kindly assign me this issue.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to uh @MonarchGitHub
