### ISSUE TITLE
Logo misalignment in footer and adding icons under follow us on FAQ page

### ISSUE THREAD

**Issue by dude-curious** [Rayman-Sodhi/Clone-IT#156]
### What happened?

![image](https://user-images.githubusercontent.com/83502872/159161839-6983397b-f9ad-4ecc-a861-881d146c0cbe.png)

I'd like to align the logo correctly and add icons below "follow us"  in the footer.

### How can we reproduce this bug?

No, it's clearly visible.

### Urgency (Optional)

Medium priority

**Comment by dude-curious** [comment]
I'm a GSSoC contributor and I'd like to work on this issue

**Comment by gurjeetsinghvirdee** [comment]
In my side it looks good

![Screenshot (751)](https://user-images.githubusercontent.com/73753957/159172280-0ec95acd-3bab-4efc-ac1b-d8e9833fbfc8.png)

**Comment by gurjeetsinghvirdee** [comment]
In Chrome, Firefox Developer Edition, and in Edge, it looks perfect @dude-curious

**Comment by dude-curious** [comment]
The FAQ page has the problem @gurjeetsinghvirdee 

Kindly recheck.

**Comment by gurjeetsinghvirdee** [comment]
> The FAQ page has the problem @gurjeetsinghvirdee
> 
> Kindly recheck.

that's y I mention in #158 to fix all issues in faq page
