### ISSUE TITLE
Fixing Navbar of FAQ page

### ISSUE THREAD

**Issue by dude-curious** [Rayman-Sodhi/Clone-IT#157]
### What happened?

![image](https://user-images.githubusercontent.com/83502872/159162197-9ed37123-b69b-4206-be64-c11931e71965.png)
Fixing the "Cloneit" logo in navbar.

### How can we reproduce this bug?

NA

### Urgency (Optional)

Medium priority

**Comment by Vijeth56** [comment]
I would like to work on this issue under gssoc22
Please assign me this issue!
