### ISSUE TITLE
Making the Navbar sticky in FAQ page

### ISSUE THREAD

**Issue by dude-curious** [Rayman-Sodhi/Clone-IT#158]
### Is your feature request related to a problem? Please describe.

Make the Navbar sticky on the FAQ page.

### Describe the solution you'd like.

I will make the Navbar sticky , clear the misalignment of the logo and add icons below 'follow us'.

**Comment by dude-curious** [comment]
I'd like to add this feature under GSSoC 22

**Comment by gurjeetsinghvirdee** [comment]
assigned to u @dude-curious

**Comment by dude-curious** [comment]
Thank you..

**Comment by gurjeetsinghvirdee** [comment]
@dude-curious all faq page changes do in 1 single issue, edit the description and fetch your upstream before making changes

**Comment by dude-curious** [comment]
Shall I close this issue?

**Comment by gurjeetsinghvirdee** [comment]
> Shall I close this issue?

not this just edit the description

**Comment by dude-curious** [comment]
Sorry but what should I add in the description.

I'm new to open source so please guide me with this.

**Comment by gurjeetsinghvirdee** [comment]
> Sorry but what should I add in the description.
> 
> I'm new to open source so please guide me with this. @gurjeetsinghvirdee

in description you add what changes you want to fix

**Comment by dude-curious** [comment]
> > Sorry but what should I add in the description.
> > 
> > I'm new to open source so please guide me with this. @gurjeetsinghvirdee
> 
> in description you add what changes you want to fix 

Done..
Does that look good?
@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
yeah it's good

**Comment by dude-curious** [comment]
Is this issue fixed now?
