### ISSUE TITLE
Enhance the LInkedIn Clone and change the   idea from ConnectedIn to LinkedIn

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#16]

**Comment by Anup0099** [comment]
I would like to work on this issue

**Comment by Anish1411** [comment]
Hey , I am a GSSoC '22 participant. Please assign me this issue.

**Comment by Anushruth-Reddy** [comment]
Hello! I'm a GSSoC'22 participant, kindly assign me this issue

**Comment by Rayman-Sodhi** [comment]
already assigned

**Comment by Anish1411** [comment]
hey @Rayman-Sodhi , what changes i have to make in likedin clone.

**Comment by gurjeetsinghvirdee** [comment]
@Anish1411 deadline was passed for this issue

**Comment by AnweshaRoses** [comment]
hello I am a Gssoc participant, can you please assign this to me

**Comment by gurjeetsinghvirdee** [comment]
> hello I am a Gssoc participant, can you please assign this to me

Assigning to u @AnweshaRoses

**Comment by AnweshaRoses** [comment]
@gurjeetsinghvirdee  To make it into a linkedIn clone I think I will have to change almost every single element so is it okay if I make another one from scratch since that will be much easier?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee To make it into a linkedIn clone I think I will have to change almost every single element so is it okay if I make another one from scratch since that will be much easier?

ok make another one
