### ISSUE TITLE
Instagram Login Page Clone using HTML, CSS

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#163]
I am **TRIDIB BAG**, GSSOC'22 contributor, wanted to add **Instagram Login Page Clone** using HTML, CSS as there is nothing on this topic . So I want to contribute on it.
Please @Rayman-Sodhi , can You assign it to me ?

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 assigned to you

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee will be done by tonight for sure

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 make sure to deploy it

**Comment by Mrjoy832** [comment]
> @Mrjoy832 make sure to deploy it

PR created ..please check
