### ISSUE TITLE
Pluralsight WebPage Clone 

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#166]
I am **TRIDIB BAG**,  GSSOC'22 contributor, wanted to add **PLURALSIGHT Landing  Page** Clone using **HTML, CSS** as there is nothing on this topic . So I want to contribute on it.

Please @Rayman-Sodhi , can You assign it to me ?

**Comment by gurjeetsinghvirdee** [comment]
Why just login page make a website clone @Mrjoy832

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee , Please assign, I will be making HULU WebPage clone

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee , Please assign, I will be making HULU WebPage clone

Already there check on link

**Comment by Mrjoy832** [comment]
Okay @gurjeetsinghvirdee , I will be adding Pluralsight Complete webpage clone...

**Comment by gurjeetsinghvirdee** [comment]
> Okay @gurjeetsinghvirdee , I will be adding Pluralsight Complete webpage clone...

Assigning to uh @Mrjoy832
