### ISSUE TITLE
Make a Hamburger in Navbar 

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#167]
In mobile responsive create a hamburger and put all menus inside it and fix logo & change the sticky position

**Comment by Vijeth56** [comment]
I would like to work on this issue under gssoc22
Please assign me!!!

**Comment by gurjeetsinghvirdee** [comment]
@Vijeth56 assign uh! you have have 5-6 days to complete it

**Comment by soumali28** [comment]
I want to work on this issue under Jwoc.

**Comment by gurjeetsinghvirdee** [comment]
@soumali28 JWOC ended

**Comment by soumali28** [comment]
Sorry it will be GSSoc. 😅

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @soumali28
