### ISSUE TITLE
Zomato HomePage Clone

### ISSUE THREAD

**Issue by StillAbeginnerr** [Rayman-Sodhi/Clone-IT#168]
### Is your feature request related to a problem? Please describe.

I want to make a clone of Homepage of zomato.com

### Describe the solution you'd like.

I will make it in CSS and React JS.

**Comment by gurjeetsinghvirdee** [comment]
@StillAbeginnerr assign to u

**Comment by gurjeetsinghvirdee** [comment]
Are u a gssoc participant?

**Comment by StillAbeginnerr** [comment]
@gurjeetsinghvirdee Yes , I am a gssoc participant

**Comment by StillAbeginnerr** [comment]
What is the deadline to complete any issue because levels are not mentioned?

**Comment by gurjeetsinghvirdee** [comment]
> What is the deadline to complete any issue because levels are not mentioned here? I have done level based issues before

5-6 days , level depends on your work

**Comment by StillAbeginnerr** [comment]
@gurjeetsinghvirdee thank you for the opportunity. I will complete the issue as soon as possible.

**Comment by StillAbeginnerr** [comment]
![image](https://user-images.githubusercontent.com/88205668/160231317-414247fb-ceab-42c8-ac68-e483121a84f0.png)

I shall complete it by tomorrow

**Comment by StillAbeginnerr** [comment]
@gurjeetsinghvirdee I have done the work, can you please merge my pull request.
