### ISSUE TITLE
WhatsApp UI Clone 

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#172]
I am **TRIDIB BAG**,  GSSOC'22 contributor, wanted to add **WhatsApp UI** Clone using **HTML, CSS** as there is nothing on this topic . So I want to contribute on it.

Please @Rayman-Sodhi , can You assign it to me ?

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi assign him, wait till she assigns you ok😁

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Mrjoy832 even I can do same things
