### ISSUE TITLE
Mac OS Clone using HTML, CSS

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#176]
I am **TRIDIB BAG**,  GSSOC'22 contributor, wanted to add **Mac OS  Clone using HTML, CSS, JS** as there is nothing on this topic . So I want to contribute on it.

Please @gurjeetsinghvirdee ,can You assign it to me ?

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Mrjoy832
