### ISSUE TITLE
Title: Create Rockstar Games Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [Rayman-Sodhi/Clone-IT#177]
### Is your feature request related to a problem? Please describe.

Yes,this website belongs to company that have created popular games like: GTA 5, GTA 4, GTA SanAndreas , GTA Vice City, GTA 3,etc

### Describe the solution you'd like.

- I will approach this using React JS

### Describe alternatives you've considered.

- At least I will do this using BootStrap

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/76027425/159493782-1114d1ed-3e27-4d1d-92a6-ffb7646a0d1e.png)

**Comment by gurjeetsinghvirdee** [comment]
@Kumar-laxmi assigned u

**Comment by gurjeetsinghvirdee** [comment]
Code copied from this repo `https://github.com/EmmanuelOkuchukwu/rockstar-social-club-clone`
@Kumar-laxmi 

@whiteHatpro
