### ISSUE TITLE
Enhance the CLONE-IT Website 

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#18]

**Comment by tusharjain365** [comment]
@Rayman-Sodhi I would like to work on this issue.

**Comment by Rayman-Sodhi** [comment]
hi @tusharjain365  plz send me a draft of what you are planning to create  and how will you add all clones in the website with same URL as this issue requires much work.And should be completed  within time

**Comment by tusharjain365** [comment]
hi, Sure, I will send it asap.

**Comment by Tanujkanti4441** [comment]
hey can i work on this

**Comment by Rayman-Sodhi** [comment]
sure
