### ISSUE TITLE
Title: Add a CodePen Clone 

### ISSUE THREAD

**Issue by mahiiverse1** [Rayman-Sodhi/Clone-IT#188]
### Is your feature request related to a problem? Please describe.

I want to work on adding a Codepen clone to this project.

### Describe the solution you'd like.

I will be using React to build a Codepen clone. Since I will be building from scratch please let me know in how much time should I build it, preferably I require 2-3 weeks.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to you @mahiiverse1 you have 1 week to complete

**Comment by mahiiverse1** [comment]
@gurjeetsinghvirdee Hi I know I'm supposed to complete this by today, and I have worked on it quite a bit just wanted to ask can I get one extra day to complete this? Since i was really busy the last week with my exams and only started working on this yesterday, and also my system was showing some errors, I'll definitely make a PR by Sunday (tomorrow)

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee Hi I know I'm supposed to complete this by today, and I have worked on it quite a bit just wanted to ask can I get one extra day to complete this? Since i was really busy the last week with my exams and only started working on this yesterday, and also my system was showing some errors, I'll definitely make a PR by Sunday (tomorrow)

No problm

**Comment by mahiiverse1** [comment]
Hi I've completed the clone Im just confused how to put it up on here and make a PR since this is my first React project I've made and also I'm new to contributing. I have certain node-modules folder with another set of folders that im not able to upload but I also noticed other projects uploaded do not have that.
Also do i need to host this website? Do i host it on github itself or something like netlify if yes? Please do help me out thanks

**Comment by gurjeetsinghvirdee** [comment]
make a .gutignore file in your project folder then write nodemodules inside there 

Like this

# dependencies
/node_modules
/.pnp

And deploy whether you want

**Comment by mahiiverse1** [comment]
ok I got it, I'll try it thanks!!

**Comment by gurjeetsinghvirdee** [comment]
> ok I got it, I'll try it thanks!!

If your issue not solved then ping me
<a href="https://discordapp.com/users/916597112882495510" target="_blank">
<img src="https://img.shields.io/badge/@Guri-5865F2?style=for-the-badge&logo=discord&logoColor=white" width="80" height="22" alt="discord">
