### ISSUE TITLE
UI of About Us section can be improved

### ISSUE THREAD

**Issue by Nitya-S27** [Rayman-Sodhi/Clone-IT#189]
### Is your feature request related to a problem? Please describe.

- There is very less space between two rows in the About Us section.

- The padding of the text box must be increased for better readability.

- Also the images are overflowing out of the box which is not looking good and can be improved.

### Describe the solution you'd like.

This issue can be resolved by adding some space between the rows and padding in the text box.

### Add any other context or screenshots about the feature request here.

![Screenshot (409)](https://user-images.githubusercontent.com/81871441/160231220-72fd8752-7f85-40bd-a269-fd8cb9e1bf9c.png)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Nitya-S27

**Comment by aaryahjolia** [comment]
Can I work on this under GSSoC ?

**Comment by gurjeetsinghvirdee** [comment]
@aaryahjolia assigned to u
