### ISSUE TITLE
AppleClone TV&Home Page 

### ISSUE THREAD

**Issue by priyanshi-2001** [Rayman-Sodhi/Clone-IT#190]
I want to add TV&Home Page in Apple Clone. Whenever user clicks on TV&Home on main page  the following page will open.
This is the page I want to make.
![issue1 1](https://user-images.githubusercontent.com/55049704/160233553-0a701848-46b8-4bf8-88b9-f583d3def07e.png)

I will make it using html,css and javascript. 

The page will have exact parallax effect as on apple website https://www.apple.com/in/tv-home/.
Kindly assign me this issue.

**Comment by gurjeetsinghvirdee** [comment]
Assign to u @priyanshi-2001

**Comment by priyanshi-2001** [comment]
Hello mam, I know its been 5 days since I have opened this issue. But I need some time. My college project submission is going on.
I will complete making the webpage of this issue by next week positively.
Thankyou.

**Comment by gurjeetsinghvirdee** [comment]
> Hello mam, I know its been 5 days since I have opened this issue. But I need some time. My college project submission is going on.
> I will complete making the webpage of this issue by next week positively.
> Thankyou.

Ok take your time, by the way I'm not mam😶‍🌫

**Comment by Rayman-Sodhi** [comment]
@priyanshi-2001  are you working on this?

**Comment by whiteHatpro** [comment]
@priyanshi-2001 update?
