### ISSUE TITLE
Create a Wikipedia Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [Rayman-Sodhi/Clone-IT#194]
### Is your feature request related to a problem? Please describe.

Yes, this is related to the problem this project deals with

### Describe the solution you'd like.

I will use HTML, JS, CSS

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/76027425/160242134-5bd91ba9-47eb-48f7-aed0-5bf775dc1d6b.png)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to you @Kumar-laxmi
