### ISSUE TITLE
Google Login Page Clone 

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#197]
Hey! I am **Tridib Bag**, GSSOC'22 Contributor, wanted to add a clone of **Google Login Page** using HTML5, CSS3 as there is nothing regarding this. 
Can @Rayman-Sodhi , @gurjeetsinghvirdee , kindly assign it to me?

**Comment by gurjeetsinghvirdee** [comment]
Closing this coz we need website clone not a login clone and google clone alreadyaafed by me

**Comment by gurjeetsinghvirdee** [comment]
> Closing this coz we need website clone not a login clone and google clone alreadyaafed by me 

Read important issue before mentioning me @Mrjoy832
