### ISSUE TITLE
Airbnb  webpage  Clone 

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#198]
Hi, I am **TRIDIB BAG**. I'm a GSSoC22 participant.
I want to add **landing page clone of Airbnb** with proper documentation as there is nothing regarding this . I'm really want to contribute in this topic .

Can @Rayman-Sodhi @whiteHatpro  please assign it to me?

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Mrjoy832
