### ISSUE TITLE
Title: Use semantic tags to make Clone-IT more accessibile

### ISSUE THREAD

**Issue by Olaleye-Blessing** [Rayman-Sodhi/Clone-IT#202]
### Is your feature request related to a problem? Please describe.

Screen readers will have problems while accessing the website.

### Describe the solution you'd like.

Use semantics tags where necessary instead of divs.

### Add any other context or screenshots about the feature request here.

This is what it currently looks like.
![Screenshot (229)](https://user-images.githubusercontent.com/70102539/160289038-d6bf45a8-979f-4b22-8685-7577bb4a3d26.png)

Those divs could be replaced with a header, nav, and sections tags.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Olaleye-Blessing
