### ISSUE TITLE
Create Nike Website Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [Rayman-Sodhi/Clone-IT#207]
### Is your feature request related to a problem? Please describe.

Yes, since this is a website clone

### Describe the solution you'd like.

I will use HTML, CSS, JS

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

-

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Kumar-laxmi
