### ISSUE TITLE
Create: Kali.org Homepage Clone

### ISSUE THREAD

**Issue by StillAbeginnerr** [Rayman-Sodhi/Clone-IT#214]
### Is your feature request related to a problem? Please describe.
I am gssoc participant and i want to put forward a proposal,

<h2>As this is an open source event , open source brands like kali linux should be included in this repository too. I can make a clone of kali.org homepage.<h2>

### Describe the solution you'd like.

Simple Homepage of Kali.org with
<hr>
My Extra Features:
<li>floating animation for kali dragon logo</li>

<hr>
technologies I want to use - React and Pure CSS

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @StillAbeginnerr

**Comment by gurjeetsinghvirdee** [comment]
Please don't copy code from anywhere either it will be get Plagiarism Content label like others get

**Comment by StillAbeginnerr** [comment]
I don't copy as it would not improve my learning , I will just take original content from the kali.org itself

**Comment by StillAbeginnerr** [comment]
Update - Floating Animation done and Header Part

![image](https://user-images.githubusercontent.com/88205668/161352653-65438e1f-41d5-4b0e-8266-2d1a7fd935ab.png)

**Comment by StillAbeginnerr** [comment]
I did my best whatever I could have done being a beginner , unfortunately I have got exams so wrapping up the best work.
