### ISSUE TITLE
Create Pizza Fan Website

### ISSUE THREAD

**Issue by GNtrazios** [Rayman-Sodhi/Clone-IT#215]
**Is your feature request related to a problem? Please describe.**
Yes, since this is a website clone

**Describe the solution you'd like.**
I will use HTML, CSS

**Describe alternatives you've considered.**

- 

**Add any other context or screenshots about the feature request here.**
Link of website -> https://www.pizzafan.gr/en

![1](https://user-images.githubusercontent.com/72870150/160465645-3c5f208c-3c30-46b3-bb20-afd5899b9a03.png)

**Comment by GNtrazios** [comment]
@[gurjeetsinghvirdee](https://github.com/gurjeetsinghvirdee) i've just create the issue and i am going to start work on it.
Could you please assign me for this task?

**Comment by gurjeetsinghvirdee** [comment]
@GNtrazios assigned to u
