### ISSUE TITLE
Add Instagram Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#222]
The choice was yours if it will be a UI or You want to make it fully functional

**Comment by Sourajita21** [comment]
Assign me this task please. I will try to give my best.

**Comment by gurjeetsinghvirdee** [comment]
Assigned uh @Sourajita21 you have a week to complete this

**Comment by Rakesh9100** [comment]
Can I work on this since it's above 1 week to be assigned to him ?

**Comment by gurjeetsinghvirdee** [comment]
> Can I work on this since it's above 1 week to be assigned to him ?

You can work on this @Rakesh9100
