### ISSUE TITLE
Add 2048 game

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#224]
2048 game using React Js

**Comment by sampavaranasi** [comment]
@Rayman-Sodhi @gurjeetsinghvirdee
 https://github.com/surajm-333/Ace-The-FrontEnd/issues/273,

**Comment by sampavaranasi** [comment]
@Rayman-Sodhi Take care in repeat ishues

**Comment by gurjeetsinghvirdee** [comment]
> @Rayman-Sodhi Take care in repeat ishues

thnku but apko ek baat pta ni shyd jo aap link dere h usme se labels hat gye h unke points add ni hue h or dusri baat ek project rhega aur jada hi taklif hai to complain krle mrko koi issue nhi h, jaiye ticket raise kre

**Comment by sampavaranasi** [comment]
@Rayman-Sodhi A doubt. Contrinutor itself adds level label theyselfes?

**Comment by gurjeetsinghvirdee** [comment]
> @Rayman-Sodhi A doubt. Contrinutor itself adds level label theyselfes?

Collaborator can do

**Comment by gurjeetsinghvirdee** [comment]
> > @Rayman-Sodhi A doubt. Contrinutor itself adds level label theyselfes?
> 
> Collaborator can do

If PA or mentor not active

**Comment by gurjeetsinghvirdee** [comment]
And after sometime I remove the labels that's y I said you can complain it if you have issues with me

**Comment by gurjeetsinghvirdee** [comment]
@sampavaranasi and haa ye jitne bhi links idhr udhr chipka re ho usse kpi fyda ni ye labels htane wale kaam me khud kr chuka har ek repo se
