### ISSUE TITLE
Image carousel in KFC Clone

### ISSUE THREAD

**Issue by shrutiverma13** [Rayman-Sodhi/Clone-IT#227]
### Is your feature request related to a problem? Please describe.

The cards in the clone are just displayed plainly in a tabular format.

### Describe the solution you'd like.

Adding an image carousel which can be scrollable.

**Comment by shrutiverma13** [comment]
Assign the issue to me.

**Comment by gurjeetsinghvirdee** [comment]
@shrutiverma13 assigned to u
