### ISSUE TITLE
Title: Styling Discord clone

### ISSUE THREAD

**Issue by Adbnemesis** [Rayman-Sodhi/Clone-IT#228]
### Is your feature request related to a problem? Please describe.

The buttons are not styled properly. They lack padding. Also the color isnt matching the real app. 

### Describe the solution you'd like.

I'd style the buttons properly and add some padding to them. Also i'll find the best color matching the real app.

**Comment by gurjeetsinghvirdee** [comment]
assigned to u @Adbnemesis
