### ISSUE TITLE
Twitch Homepage Clone

### ISSUE THREAD

**Issue by XZANATOL** [Rayman-Sodhi/Clone-IT#231]
### Is your feature request related to a problem? Please describe.

A Clone of Twitch Homepage with Dark Theme applied

### Describe the solution you'd like.

The project will make use of:
* HTML
* CSS
* Bootstrap 5

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/64689436/161282839-26fc573e-5873-4679-83d3-e82840154c88.png)

Issue made under GSSoC'22 contributions.

**Comment by gurjeetsinghvirdee** [comment]
Our Topper comes here😁😁 @XZANATOL 
assigned u
