### ISSUE TITLE
Title: Add Wordle-Clone

### ISSUE THREAD

**Issue by Akshata-Gunapache** [Rayman-Sodhi/Clone-IT#239]
### Is your feature request related to a problem? Please describe.

I wish to add a clone of Wordle website

### Describe the solution you'd like.

A website that is a clone of Wordle-The word 
![Screenshot 2022-04-02 224532](https://user-images.githubusercontent.com/96786500/161393892-72d0e874-7893-404f-b3a7-c23faa998445.png)
game

**Comment by Akshata-Gunapache** [comment]
I am GSSoC'22 participant and I would love to work on this issue with the above ideas. @Rayman-Sodhi Please assign it to me

**Comment by gurjeetsinghvirdee** [comment]
@Akshata-Gunapache hey once completed plz deploy your project and add On readme file under project folder with video

**Comment by Akshata-Gunapache** [comment]
I am done with my project. I just need to deploy it .

**Comment by Akshata-Gunapache** [comment]
> @Akshata-Gunapache hey once completed plz deploy your project and add On readme file under project folder with video

@gurjeetsinghvirdee How to I go ahead with this step ? Please guide.

**Comment by gurjeetsinghvirdee** [comment]
@Akshata-Gunapache sorry I didn't I have my exams going on so little bit busy
deploy with vercel it will automatically deploy your project

just signup and connect your Github repo after that choose the project repo you want to deploy then hit the deploy button in 2-3 mins deployed site ready.

**Comment by gurjeetsinghvirdee** [comment]
if you direct add wordle clone here then make a new repo and push all code after that deploy with vercel

**Comment by Akshata-Gunapache** [comment]
> if you direct add wordle clone here then make a new repo and push all code after that deploy with vercel

@gurjeetsinghvirdee  How do I add it directly here?

**Comment by Akshata-Gunapache** [comment]
> @Akshata-Gunapache are you free tomorrow so we share the screen and deploy your project

Yes sure that would be great . What time and date?

**Comment by Akshata-Gunapache** [comment]
And could you please provide me the details about the meet? Thank You .

**Comment by gurjeetsinghvirdee** [comment]
> And could you please provide me the details about the meet? Thank You .

You are in discord, So ping me there If someone saw this maybe they can misuse

**Comment by Akshata-Gunapache** [comment]
Yes sure .
