### ISSUE TITLE
Change Position of  scroll up button . Chatbot and Scroll up button  are intermixed.

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#242]

**Comment by Akshata-Gunapache** [comment]
@Rayman-Sodhi Hi, I am a GSSoC'22 participant. I would like to work on this issue . Could you please assign it to me and also send me the details of the issue or a screenshot showing the problem?

**Comment by gurjeetsinghvirdee** [comment]
There were no ss bcoz in last PR 
I changed some css and that scroll button was out of the screen right now 

If you can check your browser in 70-80% zoom then it will show from left side
