### ISSUE TITLE
bug: fix Hamburger 

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#257]
### What happened?

Fix Hamburger in Mobile responsive, It covers all things in site
![Screenshot (800)](https://user-images.githubusercontent.com/73753957/161514438-8b50a897-5ecd-4bb2-a6c9-a0eddd9110f3.png)

### How can we reproduce this bug?

Chang color or add a background bcoz that a white color if I open a hamburger in the white background then it will be not shown so fix it

### Urgency (Optional)

Medium priority

**Comment by Adhetya** [comment]
Can you assign issue to me? I am GSSOC 22 contributor

**Comment by gurjeetsinghvirdee** [comment]
sure @Adhetya
