### ISSUE TITLE
W3 schools Homepage

### ISSUE THREAD

**Issue by StillAbeginnerr** [Rayman-Sodhi/Clone-IT#262]
### Description

I am gssoc participant and i want to make a landing page frontend clone of W3 schools website - https://www.w3schools.com/

Tech stack - html , css and javascript

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by StillAbeginnerr** [comment]
Due to some problems, couldn't work much but now continuing and nav-bar completed (mobile-responsive)
![image](https://user-images.githubusercontent.com/88205668/162608916-ec7f51c4-fd9f-4e0f-8453-ce9d07266259.png)

**Comment by StillAbeginnerr** [comment]
![image](https://user-images.githubusercontent.com/88205668/163005656-1ba66328-fe23-4e14-b2c1-ae7dcbbf0ee8.png)
![image](https://user-images.githubusercontent.com/88205668/163005727-0e1eb31d-d74a-4073-9cbf-361ef1eb1e3a.png)

Will it be okay for level 3 if i make it responsive?

**Comment by StillAbeginnerr** [comment]
@Rayman-Sodhi i have nearly completed , just css for responsive design left.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee  i have nearly completed , just css for responsive design left.
> 
> Will it be okay for level 3 if i make it responsive?

Omg just feel like real and too beautiful💗

**Comment by gurjeetsinghvirdee** [comment]
Bro deploy it @StillAbeginnerr

**Comment by StillAbeginnerr** [comment]
http://w3-schools-clone-frontend.vercel.app/
++ mobile responsive

**Comment by StillAbeginnerr** [comment]
![image](https://user-images.githubusercontent.com/88205668/163214725-939607a7-c4fd-4664-b802-260381d9d93c.png)

i hope it will get level 3 because it is also mobile responsive

**Comment by gurjeetsinghvirdee** [comment]
bro why close this I'm lit busy that's y I didn't check @StillAbeginnerr

**Comment by gurjeetsinghvirdee** [comment]
I'm Mentor, contributor even a Tech team member I have to see all things and I have also

**Comment by gurjeetsinghvirdee** [comment]
Hehe I didn't see

**Comment by StillAbeginnerr** [comment]
No problem , i thought i could reduce your work of closing an issue.
