### ISSUE TITLE
bug: Fix footer

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#268]
### What happened?

someone added extra footer in code

### How can we reproduce this bug?

Remove the extra footer

### Urgency (Optional)

High priority

**Comment by Rakesh9100** [comment]
In which code are you talking about ?

**Comment by gurjeetsinghvirdee** [comment]
About this that white part 


![Screenshot_2022-04-05-09-24-06-757_com android chrome](https://user-images.githubusercontent.com/73753957/161675816-5cc0542a-707a-49b6-b02c-c2a6005106b3.jpg)

**Comment by Rakesh9100** [comment]
Can i work on this issue ?

**Comment by gurjeetsinghvirdee** [comment]
Sure @Rakesh9100 assigned to u
