### ISSUE TITLE
Add Google Clone

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Rayman-Sodhi/Clone-IT#27]
Assign me this Issue.

**Comment by Rayman-Sodhi** [comment]
Are you working on this issue?

**Comment by Sulagna-Dutta-Roy** [comment]
Yes. Please check my PR

**Comment by Rayman-Sodhi** [comment]
you have not made a pr .You can pull the recent changes and then make a pull request..Dont make the PR without updating
