### ISSUE TITLE
Add Clone of Hulu - Stream TV

### ISSUE THREAD

**Issue by Rakesh9100** [Rayman-Sodhi/Clone-IT#278]
### Description

Can I add the clone of most popular Stream TV and Movies -- Hulu ?

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Hulu is already there on the site you can check here https://rayman-sodhi.github.io/Clone-IT/

**Comment by gurjeetsinghvirdee** [comment]
I'm closing this issue because Hulu already in this repo
