### ISSUE TITLE
Netflix landing page clone

### ISSUE THREAD

**Issue by D-Palamala-Sai-Niharika** [Rayman-Sodhi/Clone-IT#3]
@Rayman-Sodhi  I am very much interested in creating netflix clone. So i would like to contribute to this repository. Can u please assign me this issue

**Comment by Rayman-Sodhi** [comment]
Sure , I will look into labels and grading system then assign you the

**Comment by SushantPatial** [comment]
I can help too if you wish. I made a netflix clone before https://sushantpatial.github.io/Netflix-Clone/

**Comment by Rayman-Sodhi** [comment]
Hi @D-Palamala-Sai-Niharika  you can add your role in the excel sheet and start working on this issue

**Comment by D-Palamala-Sai-Niharika** [comment]
@Rayman-Sodhi  My comment in excel sheet has been resolved today .I will add my role and start working thank you
