### ISSUE TITLE
Adding a city filter option

### ISSUE THREAD

**Issue by warriorBunny013** [Rayman-Sodhi/Clone-IT#301]
### Is your feature request related to a problem? Please describe.

![Screenshot (113)](https://user-images.githubusercontent.com/97738453/162568777-38e2d9f8-41fe-4d1c-a207-1610308b8a34.png)

### Describe the solution you'd like.

i want to ADD the feature of selecting different cities.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @warriorBunny013

**Comment by Rayman-Sodhi** [comment]
@warriorBunny013 are you working on this?
