### ISSUE TITLE
adding lists of items in flipkart clone

### ISSUE THREAD

**Issue by warriorBunny013** [Rayman-Sodhi/Clone-IT#302]
### Is your feature request related to a problem? Please describe.

![Screenshot (114)](https://user-images.githubusercontent.com/97738453/162569043-cbe7e987-7e5f-4e88-aa66-093ba285303f.png)

### Describe the solution you'd like.

hovering those we'll get lists of all the items

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @warriorBunny013

**Comment by Rayman-Sodhi** [comment]
@warriorBunny013  are you working on this?
