### ISSUE TITLE
Modification of Instagram Clone Login Page and Merge Instagram-Clone and Login Clone in one folder

### ISSUE THREAD

**Issue by Rakesh9100** [Rayman-Sodhi/Clone-IT#304]
### Is your feature request related to a problem? Please describe.

The Instagram original login page is different from this clone login in this project.

### Describe the solution you'd like.

I want to modify the Instagram Login Page clone and make it similar and same as official Instagram Login page. 
I would also merge the Instagram Login page clone and Instagram Clone added by me in one folder to make it look well good.
We can even give dummy credentials to make the workflow mimic like butter.

## The official Instagram Login Page :--
![3](https://user-images.githubusercontent.com/73993775/162574015-dec2be46-0fc5-4431-bc12-8c20f231357f.jpg)

## This project login page clone :--
![2](https://user-images.githubusercontent.com/73993775/162573942-f4e905a0-6988-4032-9ac7-6433c21f84f6.png)

**Comment by gurjeetsinghvirdee** [comment]
assigned u @Rakesh9100

**Comment by Rakesh9100** [comment]
> assigned u @Rakesh9100

Okay Thanks
