### ISSUE TITLE
Make github clone responsive

### ISSUE THREAD

**Issue by Adhetya** [Rayman-Sodhi/Clone-IT#309]
### What happened?

The github clone website published in this website is not mobile responsive. Also, the font does not look very good.

### How can we reproduce this bug?

Go the github clone in https://rayman-sodhi.github.io/Clone-IT/

### Desktop Information (Optional)

<img width="1440" alt="Screenshot 2022-04-10 at 3 04 05 PM" src="https://user-images.githubusercontent.com/20537150/162612029-83f91107-5b87-4f19-ae6a-c2d98d1994ed.png">

**Comment by gurjeetsinghvirdee** [comment]
assigned to u @Adhetya
