### ISSUE TITLE
Spacex Landing page clone: 

### ISSUE THREAD

**Issue by VaibhavUpreti** [Rayman-Sodhi/Clone-IT#311]
### Description

This is a simple clone of spacex.com webpage made with HTML,CSS & JS which is fully responsive.

Contribution made as a GSSOC'22 participant.

![spacex](https://user-images.githubusercontent.com/85568177/162623956-e9581361-14c7-4739-ba14-6b077f8190c0.jpeg)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by ayush-sleeping** [comment]
@VaibhavUpreti , without even crosschecking how you make a issue with the same content , 
SpaceX Clone #287
here I have also explain that what I am going to clone ,......................
#

I have created this issue 6 days ago , as a GSSOC participant ............ and you have make this issue 2 days ago . 
which is strictly not allow in GSSOC guidelines .

#

**Comment by VaibhavUpreti** [comment]
Hey @ayush-sleeping , Sorry I missed your issue.... It was unintentional & I just missed it. @gurjeetsinghvirdee ur free to remove my changes and allow him to push his project

**Comment by ayush-sleeping** [comment]
> Hey @ayush-sleeping , Sorry I missed your issue.... It was unintentional & I just missed it. @gurjeetsinghvirdee ur free to remove my changes and allow him to push his project

thanks buddy , I was freakout after seeing this

**Comment by VaibhavUpreti** [comment]
Yea I'm really sorry, Happy contributing @ayush-sleeping :)

**Comment by ayush-sleeping** [comment]
> Yea I'm really sorry, Happy contributing @ayush-sleeping :)

and I am sorry .... because i was rude in comment ..............
