### ISSUE TITLE
Navbar needs modification

### ISSUE THREAD

**Issue by Olaleye-Blessing** [Rayman-Sodhi/Clone-IT#318]
### What happened?

Nav links overlap the site's title at some media queries. This is most likely to happen on Ipads since I tested this on a laptop.

![Screenshot (308)](https://user-images.githubusercontent.com/70102539/162645880-36da9985-aa26-461b-af30-37b532255b79.png)

### How can we reproduce this bug?

Go to [Clone-IT](https://rayman-sodhi.github.io/Clone-IT/), probably on a laptop.

1. On Firefox browser
    -  press `ctrl + shift + M` to view responsive design.
    -  Choose **iPad Mini** as your device or choose to width of 516

2. On chrome or Brave browser
    - press `ctrl + shift + I`, then `ctrl + shift + M`
    - Choose width of 548

![Screenshot (309)_LI](https://user-images.githubusercontent.com/70102539/162646286-c11b4b58-aaff-40dc-a07d-10d86d798a46.jpg)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Olaleye-Blessing
