### ISSUE TITLE
Title: pressing enter should search/open project

### ISSUE THREAD

**Issue by Olaleye-Blessing** [Rayman-Sodhi/Clone-IT#319]
### Is your feature request related to a problem? Please describe.

I need to take my mouse to the search icon and click on it before my searched project could be opened.

### Describe the solution you'd like.

Pressing `enter button` should open the project if found.

### Add any other context or screenshots about the feature request here.

![Screenshot (310)_LI](https://user-images.githubusercontent.com/70102539/162647468-29d76f58-28c3-4f35-aa3a-d46960855424.jpg)

The search icon needs to be pressed before a search could be done.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Olaleye-Blessing
