### ISSUE TITLE
Title: Swiggy Clone Home page

### ISSUE THREAD

**Issue by kalashvasaniya** [Rayman-Sodhi/Clone-IT#329]
### Is your feature request related to a problem? Please describe.

Hey I made Swiggy Clone Project Which Is Very Good!

### Describe the solution you'd like.

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript.

### Describe alternatives you've considered.

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

**Comment by gurjeetsinghvirdee** [comment]
assigned u @kalashvasaniya
