### ISSUE TITLE
Updating the README.md file with contributor's link for this repo and Adding a section for Mentors

### ISSUE THREAD

**Issue by muhammadgalhoum** [Rayman-Sodhi/Clone-IT#336]
### Is your feature request related to a problem? Please describe.

Yes, the README.md file is very important in any repo so I want to improve it by adding the contributor's link for this repo 

### Describe the solution you'd like.

I wanna add a link to the contributor's link for this repo in the README.md file and also adding a section for Mentors

**Comment by muhammadgalhoum** [comment]
**Can you please assign this issue to me @gurjeetsinghvirdee**

**Comment by muhammadgalhoum** [comment]
Yes please assign me @gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
assigned already

**Comment by muhammadgalhoum** [comment]
![s2](https://user-images.githubusercontent.com/56798376/163210535-72b958b8-67a8-45c8-b0c2-3f470963f09f.PNG)
![s1](https://user-images.githubusercontent.com/56798376/163210542-b722ea94-37c3-4489-9397-fbe31b623ed9.PNG)

You assign this issue to you and I want you to assign it to me as GSSoC @gurjeetsinghvirdee 
Can you please assign it for me

**Comment by gurjeetsinghvirdee** [comment]
Oh sorry 😅
