### ISSUE TITLE
Google Meet Clone

### ISSUE THREAD

**Issue by Priyanshi136** [Rayman-Sodhi/Clone-IT#339]
### Description

As we all know about the google meet app, one of the best app for online meetings and video conferencing. Hence as an gssoc'22 contributor, i want to work on this app clone.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Priyanshi136

**Comment by whiteHatpro** [comment]
@Priyanshi136 update?

**Comment by Priyanshi136** [comment]
Sorry, for the delay. My exams were going on. So not able to give the time. I will raise it agian once i am ready. Thank you.
