### ISSUE TITLE
Tumblr clone

### ISSUE THREAD

**Issue by StillAbeginnerr** [Rayman-Sodhi/Clone-IT#342]
### Description

I wanna make a clone of tumblr.com landing page -> https://www.tumblr.com/explore/trending
![image](https://user-images.githubusercontent.com/88205668/163271793-141405b3-ea12-481e-af57-94a61a6a3229.png)

I will make it awesome with - responsive design , good  visuals and interacting buttons like original site.

I am a gssoc participant and my tech stack will be  html , css and react js.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by StillAbeginnerr** [comment]
please assign me this project

**Comment by StillAbeginnerr** [comment]
@gurjeetsinghvirdee bro , can you please add a pinned label to prevent unassigning , because it would take me more  than 7 days to make a same clone with some extra features of my own.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee bro , can you please add a pinned label to prevent unassigning , because it would take me more  than 7 days to make a same clone with some extra features of my own.

Ok I will pin you if github action remove you

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee bro , can you please add a pinned label to prevent unassigning , because it would take me more  than 7 days to make a same clone with some extra features of my own.

Now it will be ok

**Comment by StillAbeginnerr** [comment]
![image](https://user-images.githubusercontent.com/88205668/165192460-2f06ece0-c7bf-41ea-8fc5-9a4da9e012b8.png)
@gurjeetsinghvirdee is it okay bro ?

**Comment by StillAbeginnerr** [comment]
I couldn't get gather the backend data. is it okay for level3 pull request with mobile responsive design

**Comment by StillAbeginnerr** [comment]
https://tumblr-clone-one.vercel.app/

**Comment by gurjeetsinghvirdee** [comment]
bro if you can't fetch data from the backend or JSON file then better to write it in the frontend in js files, that looks better

**Comment by StillAbeginnerr** [comment]
okay bro
