### ISSUE TITLE
[New Issue]: google home page ui

### ISSUE THREAD

**Issue by RAHULBAWA777** [Rayman-Sodhi/Clone-IT#344]
### Description

Description of the project here - i'll be adding google homepage UI 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
@RAHULBAWA777 google clone is already here, so make something unique, before making Issue Plz check it, If it has existed on the repo or not at this time I'm closing this issue
