### ISSUE TITLE
Google Classroom Clone

### ISSUE THREAD

**Issue by khushigupta123** [Rayman-Sodhi/Clone-IT#345]
### Description

I want to create a google classroom clone using the following tech stack:

- HTML
- CSS
- Javascript

I am a GSSOC 22 contributor,
kindly assign me this issue.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @khushigupta123

**Comment by whiteHatpro** [comment]
@khushigupta123 update?

**Comment by khushigupta123** [comment]
@

> @khushigupta123 update?

Sorry for the delay, actually my sessional exams are going on, but I will create a pull request for this issue in 2-3 days for sure

**Comment by sethu400** [comment]
Shall I work on this issue?

**Comment by gurjeetsinghvirdee** [comment]
yeah sure @sethu400
