### ISSUE TITLE
The navbar and footer of FAQ page aren't consistent with that of Homepage

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [Rayman-Sodhi/Clone-IT#346]
### What happened?

The navbar and footer CSS is distorted on FAQ page, also the hover functionality, font-weight, size are not consistent with that of the Homepage.

Homepage Navbar Footer : -
![image](https://user-images.githubusercontent.com/54144759/163543891-81d3c7c5-af78-48db-ad4d-d145b70f7d1a.png)
![image](https://user-images.githubusercontent.com/54144759/163543946-44a9ffd2-7715-49bf-b514-49f256d56245.png)

FAQ Navbar :- 
![image](https://user-images.githubusercontent.com/54144759/163543842-352ee540-371b-44c7-9a8b-495ea7c2a6e8.png)
![image](https://user-images.githubusercontent.com/54144759/163543986-ecd20a03-ed26-4858-adcd-03b9ea6085a7.png)

### How can we reproduce this bug?

No reproduction needed..... It's component consistency issue

### Urgency (Optional)

Medium priority

**Comment by GaganpreetKaurKalsi** [comment]
Kindly assign me this issue under Gssoc 2022 contribution

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @GaganpreetKaurKalsi
