### ISSUE TITLE
SpaceX HomePage Clone

### ISSUE THREAD

**Issue by Sukriti-m** [Rayman-Sodhi/Clone-IT#349]
### Description

I want to create a SpaceX HomePage Clone using the following tech stack:

- HTML

- CSS

- Javascript

I'd be grateful if you could assign this task to me under GSSoC22.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
@Sukriti-m assigned to u
