### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#350]
### What happened?

The links for  amazon ,gmail and windows 11 Clone are not working

### How can we reproduce this bug?

@gurjeetsinghvirdee  Kindly add the links

**Comment by gurjeetsinghvirdee** [comment]
> ### What happened?
> 
> The links for  amazon ,gmail and windows 11 Clone are not working
> 
> ### How can we reproduce this bug?
> 
> @gurjeetsinghvirdee  Kindly add the links
> 
> ### Desktop Information (Optional)
> 
> _No response_
> 
> ### Urgency (Optional)
> 
> _No response_

Not deployed that's y not working

**Comment by VaibhavUpreti** [comment]
Gmail - (https://fluffy-mousse-bedaef.netlify.app/)...... here u can add this one
Windows 11 - (https://windows-11-static.netlify.app/)..... this one is working before 
And I tried hosting the amazon clone it was giving some build error

@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
> Gmail - (https://fluffy-mousse-bedaef.netlify.app/)...... here u can add this one
> Windows 11 - (https://windows-11-static.netlify.app/)..... this one is working in the latest push. 
> And I tried hosting the amazon clone it was giving some build error
> 
> @gurjeetsinghvirdee 

Thanks for this I will do something for amazon
