### ISSUE TITLE
[New Issue]: To add codechef homepage clone

### ISSUE THREAD

**Issue by SarthakSKumar** [Rayman-Sodhi/Clone-IT#358]
### Description

I would like to add the CodeChef Homepage Clone to the repo.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Thank you @gurjeetsinghvirdee
