### ISSUE TITLE
Adding clone of pinterest website 

### ISSUE THREAD

**Issue by Divya2163** [Rayman-Sodhi/Clone-IT#359]
### Description

I would like to create a clone of Pinterest with HTML, CSS, and Javascript. I would like to work on this under gssoc'22.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Divya2163

**Comment by VaibhavUpreti** [comment]
There is already a clone of pinterest in the project list 
https://github.com/Rayman-Sodhi/Clone-IT/tree/main/pinterest
@Divya2163 
@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
> There is already a clone of pinterest in the project list 
> https://github.com/Rayman-Sodhi/Clone-IT/tree/main/pinterest
> @Divya2163 
> @gurjeetsinghvirdee 

Ohk I forgot
