### ISSUE TITLE
Add Behance Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#361]
### Description

Behance Clone with react js

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by whiteHatpro** [comment]
@gurjeetsinghvirdee update?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee update?
> 
> 

Bro u are not a mentor anymore on this project so better to not comment on any issues or PR

**Comment by whiteHatpro** [comment]
> > @gurjeetsinghvirdee update?
> 
> Bro u are not a mentor anymore on this project so better to not comment on any issues or PR

I talked to the technical lead man
I am in the clan
