### ISSUE TITLE
Reduce size of project by using images on cloud rather than in assets folder

### ISSUE THREAD

**Issue by VaibhavUpreti** [Rayman-Sodhi/Clone-IT#364]
### Is your feature request related to a problem? Please describe.

I think we should remove heavy images and logos that we use for our websites and rather just use links in the code base

### Describe the solution you'd like.

I want to remove the assets of my projects (pint. and zara clone) and replace then with links.

And also advice new contributors to follow the same.... 

### Describe alternatives you've considered.

Also I can do this for the main website as well if the mentors agree to it.

**Comment by gurjeetsinghvirdee** [comment]
You can resduce the size by imgbot also

**Comment by gurjeetsinghvirdee** [comment]
#365
