### ISSUE TITLE
Medium UI clone

### ISSUE THREAD

**Issue by Divya2163** [Rayman-Sodhi/Clone-IT#366]
### Description

A clone of the blogging website Medium. Clone of the homepage of Medium website using HTML and CSS. CLone of the below-given website. I don't have a working model but I can work on it under gssoc'22.
![Screenshot 2022-04-17 162349](https://user-images.githubusercontent.com/76438709/163711399-58367d6c-2243-4bda-bbc3-dbd8bbb94de2.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by Divya2163** [comment]
Kindly assign me this under gssoc'22.

**Comment by gurjeetsinghvirdee** [comment]
@Divya2163 assigned to u

**Comment by sethu400** [comment]
Shall I work on this?

**Comment by gurjeetsinghvirdee** [comment]
@sethu400 assigned u
