### ISSUE TITLE
[New Issue]: Instagram clone for website

### ISSUE THREAD

**Issue by kalashvasaniya** [Rayman-Sodhi/Clone-IT#368]
### Description

Hey I made Instagram clone Which Is Very Good!

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript.

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
It's already there
