### ISSUE TITLE
Fix the navbar in 'my profile' section of LinkedIn Clone

### ISSUE THREAD

**Issue by Sanjanabharadwaj25** [Rayman-Sodhi/Clone-IT#37]
I would like to work on this.

**Comment by Rayman-Sodhi** [comment]
what is the issue please send a ss

**Comment by Sanjanabharadwaj25** [comment]
This is the home page
![image](https://user-images.githubusercontent.com/77878089/149148096-5055ce9f-6a80-4b4f-a2ba-c2673c8deb01.png)
This is the navbar in my profile page
![image](https://user-images.githubusercontent.com/77878089/149148212-3d15e1e8-c2a9-46fa-8fbb-9b54f46c9c45.png)
