### ISSUE TITLE
Title: Add Images for   modals in website

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#371]
### Is your feature request related to a problem? Please describe.

 Add  new cover image for whatsapp ui ,zara ,wikipedia and zomato clone

### Describe the solution you'd like.

Add new images and add screenshots before making a pr

**Comment by aaryahjolia** [comment]
Can I work on this under GSSoC ?

**Comment by Rayman-Sodhi** [comment]
@aaryahjolia  assigned u
