### ISSUE TITLE
Ola Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Rayman-Sodhi/Clone-IT#375]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Clone Of Ola Website

The idea behind this project
This is a very mini project which looks similar to the famous cabs website OLA

Please refer to the images below:
![ss1](https://user-images.githubusercontent.com/76146796/164028862-dc61adc9-bd92-4ce9-a7a9-6b0b6a5ea3d8.png)
![ss2](https://user-images.githubusercontent.com/76146796/164028870-a59b8194-72c6-4131-8638-f89f5ed13824.png)
![ss3](https://user-images.githubusercontent.com/76146796/164028875-7581c1d6-fea2-43c4-9728-0fce37f68619.png)
![ss4](https://user-images.githubusercontent.com/76146796/164028880-ad6089f3-be14-4145-ba9a-9a7ef1472910.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
#376
