### ISSUE TITLE
Google Shopping Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#380]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Clone Of Google Shopping Website

The idea behind this project
This is a very mini project which looks similar to the famous shopping website Google Shopping.

Please refer to the images below:
![ss1](https://user-images.githubusercontent.com/94470209/164187801-7d0dc515-672b-4c0c-b7fb-84970edf0cf3.png)
![ss2](https://user-images.githubusercontent.com/94470209/164187840-90d78999-26a2-4528-b788-954a804927df.png)
![ss3](https://user-images.githubusercontent.com/94470209/164187887-872bedb2-0773-4870-b9fd-8329c2e3fee5.png)
![ss4](https://user-images.githubusercontent.com/94470209/164187906-a53608b4-55e7-40d7-b94d-6d15ce391878.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by Rayman-Sodhi** [comment]
hey, @SupriyaGembali this website clone has been found to be under plagiarised content by the team.If you have any proof of it being genuine kindly share the proof ,otherwise this will be labeled invalid
