### ISSUE TITLE
Food Panda Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#384]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Food Panda Website Clone

### The idea behind this project
This is a well Known Food ordering Website
Please refer to the images below:
<img width="1245" alt="ss1" src="https://user-images.githubusercontent.com/94470209/164272820-07b3c91e-1a6f-4d20-949a-f7f6bab0363b.png">
<img width="1245" alt="ss2" src="https://user-images.githubusercontent.com/94470209/164272849-28ff45a7-a14e-412c-a051-09e76f61333e.png">
<img width="1245" alt="ss3" src="https://user-images.githubusercontent.com/94470209/164272865-7c830427-e925-4ca7-a09d-6407e4467388.png">
<img width="1245" alt="ss4" src="https://user-images.githubusercontent.com/94470209/164272887-fe248064-fb66-4191-9d18-f51a3a710bc8.png">
<img width="1245" alt="ss5" src="https://user-images.githubusercontent.com/94470209/164272902-12d4b36c-f92c-49f3-83ba-c3e3d7890996.png">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by Rayman-Sodhi** [comment]
hey, @SupriyaGembali this website clone has been found to be under plagiarised content by the team.If you have any proof of it being genuine kindly share the proof ,otherwise this will be labeled invalid

**Comment by SupriyaGembali** [comment]
@Rayman-Sodhi This project was made as a team work in our semester academics project where we are required to make the websites as they are...This is not plagiarized , it was written by the team as a part of work

**Comment by gurjeetsinghvirdee** [comment]
Let me clear one thing, In Tier 3 colleges you can't learn about Javascript or Front End Development & even college doesn't ask you to make a project like these cloning websites, if you have proof you make in college as a project or assignment attach here either all your PR goes to invalid

We are in college, we know that HTML, CSS & JavaScript is not a part of the course and they didn't ask you to make these type of projects, they will ask you to make real-world projects like banking system library system, etc...


@Rayman-Sodhi If she attaches proof then ok either remove all labels from merged PR
