### ISSUE TITLE
Rapido Bike Taxi Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Rayman-Sodhi/Clone-IT#391]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Clone Of Rapido Bike Taxi Website

The idea behind this project
This is a very mini project which looks similar to the famous Website Rapido Bike Taxi .

Please refer to the images below:
![ss1](https://user-images.githubusercontent.com/76146796/164525217-54794c7c-33fe-47a8-ac6b-3596808a8dc3.png)
![ss2](https://user-images.githubusercontent.com/76146796/164525234-dd6ae953-ebfc-4f7d-831d-0d5cc43bd7ef.png)
![ss3](https://user-images.githubusercontent.com/76146796/164525239-248cbd25-dca6-4314-bbaa-4603d402a3f9.png)
![ss4](https://user-images.githubusercontent.com/76146796/164525242-dc5d8b33-8224-4700-b54c-e88b0dea74a3.png)
![ss5](https://user-images.githubusercontent.com/76146796/164525248-919fe1cc-bcc5-4d40-8337-a453371a4bd6.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @eswarbhageerath
