### ISSUE TITLE
Paytm Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#392]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Paytm Website Clone

The idea behind this project
This is a well Known Payment Website
Please refer to the images below:
<img width="960" alt="sss1" src="https://user-images.githubusercontent.com/94470209/164531160-c11ee7b3-0f2e-425e-8b35-23a238db609d.png">
<img width="960" alt="sss2" src="https://user-images.githubusercontent.com/94470209/164531186-2d3b640b-3cd0-4d48-a30d-013a79eb422b.png">
<img width="960" alt="sss3" src="https://user-images.githubusercontent.com/94470209/164531198-16e7755b-dbbd-49ce-9c20-e8e74ee98b59.png">
<img width="960" alt="sss4" src="https://user-images.githubusercontent.com/94470209/164531226-771276ba-80d9-4678-901c-1ff8a7578caa.png">
<img width="960" alt="sss5" src="https://user-images.githubusercontent.com/94470209/164531250-29cef6b8-7292-4f3a-8c5e-0a6f6f9cc01f.png">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @SupriyaGembali

**Comment by Rayman-Sodhi** [comment]
hey, @SupriyaGembali this website clone has been found to be under plagiarised content by the team.If you have any proof of it being genuine kindly share the proof ,otherwise this will be labeled invalid
