### ISSUE TITLE
Ikea Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Rayman-Sodhi/Clone-IT#393]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Clone Of Ikea Website

The idea behind this project
This is a very mini project which looks similar to the famous Website Ikea Furnitures

Please refer to the images below:
![ss1](https://user-images.githubusercontent.com/76146796/164602683-4ce0fc1c-06c1-4e74-9689-ec7653806b13.png)
![ss2](https://user-images.githubusercontent.com/76146796/164602706-105f673a-a4f4-4ca6-b941-1cb31e5fca1e.png)
![ss3](https://user-images.githubusercontent.com/76146796/164602723-77c7d0b2-8e9c-467d-b834-0a6ad81f1bb0.png)
![ss4](https://user-images.githubusercontent.com/76146796/164602732-0aacd9d3-ddea-4d56-aa94-16f43550e886.png)
![ss5](https://user-images.githubusercontent.com/76146796/164602744-f67be90b-d687-4741-a519-62e45cf58d70.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @eswarbhageerath
