### ISSUE TITLE
Girlscript Summer Of Code(GSSoC) Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#394]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Girlscript Summer Of Code(GSSoC) Website Clone.

The idea behind this project
This is a well Known Beginner Friendly Open Source Contribution Initiative Girlscript Summer Of Code(GSSoC). 
Please refer to the images below:
<img width="955" alt="ss1" src="https://user-images.githubusercontent.com/94470209/164609346-9d059cb9-d131-4527-8d88-844dad1fb50d.png">
<img width="960" alt="ss2" src="https://user-images.githubusercontent.com/94470209/164609431-5fe252fd-153e-46c9-a62b-28309e1e4d9e.png">
<img width="960" alt="ss3" src="https://user-images.githubusercontent.com/94470209/164609612-a472cd04-eff5-432c-9466-aaa498ec4990.png">
<img width="960" alt="ss4" src="https://user-images.githubusercontent.com/94470209/164609679-14c41c59-bf8e-49b0-83bd-0deca5cbfd9d.png">
<img width="960" alt="ss5" src="https://user-images.githubusercontent.com/94470209/164609721-dbe84127-ac7e-49c3-b0e3-5e74b2a9ca59.png">
<img width="960" alt="ss6" src="https://user-images.githubusercontent.com/94470209/164609776-03221a96-5543-4384-aa68-07cd0dd44052.png">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @SupriyaGembali

**Comment by Rayman-Sodhi** [comment]
hey, @SupriyaGembali this website clone has been found to be under plagiarised content by the team.If you have any proof of it being genuine kindly share the proof ,otherwise this will be labeled invalid
