### ISSUE TITLE
Bumble Website Clone

### ISSUE THREAD

**Issue by StillAbeginnerr** [Rayman-Sodhi/Clone-IT#397]
### Description

https://bumble.com/en-in/    I want to clone this website , I will make an exact clone of it and mobile responsive version.

I will make it in HTML,CSS and JS.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
are you still working on this issue @StillAbeginnerr
