### ISSUE TITLE
Create Readme for the Project 

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#4]
Requires Description about the Project and guidelines for contribution .Can  later include contributors too.

**Comment by ayush-sleeping** [comment]
hey, @Rayman-Sodhi 
I want to work on this issue , I want to make Impressive Readme for this awesome Repo. .
For further process, `  " Assign "  ` me this issue .

**Comment by Rayman-Sodhi** [comment]
Hi, you can start creating the template . I will assign you this one as soon as I add the label for SWOC

**Comment by Rayman-Sodhi** [comment]
You can take reference from other projects  too and create a template with necessary instructions.

**Comment by ayush-sleeping** [comment]
> Hi, you can start creating the template . I will assign you this one as soon as I add the label for SWOC

ok,

**Comment by ayush-sleeping** [comment]
hey @Rayman-Sodhi , my readme work is completed .
Can you tell me , When I can push PR.

**Comment by Rayman-Sodhi** [comment]
Hi @ayush-sleeping  you can add your role in the excel sheet and start working on this issue

**Comment by ayush-sleeping** [comment]
> Hi @ayush-sleeping you can add your role in the excel sheet and start working on this issue

I have added now, Kindly checkout .

**Comment by ayush-sleeping** [comment]
@Rayman-Sodhi , Kindly tell me , 
When can I start making PR .

**Comment by Rayman-Sodhi** [comment]
can you send me ss of the readme ,I can have a look

**Comment by ayush-sleeping** [comment]
> can you send me ss of the readme ,I can have a look

https://github.com/ayush-sleeping/Clone-IT 
Checkout here and if you want me to add some other things , Let me know ..........

**Comment by Rayman-Sodhi** [comment]
This  Looks good .Can you increase the size of few headlines:
**This the place, Where you can find Clone of some of the best Websites.**
**Table of Contents :**
**Available Clones:**
**Thanks to all the people who contribute**
**Never made an open source contribution before? Wondering how contributions work in the in our project? Here's a quick rundown!**
 
![wed](https://user-images.githubusercontent.com/65675692/146207577-62161f0b-213c-4c41-bd0e-c1924d25659d.PNG)

Also ,for the guidelines : refer to the image 
![wed](https://user-images.githubusercontent.com/65675692/146207706-c91c4eeb-6d61-401c-b7f3-d76a37634a4c.PNG)

**Comment by ayush-sleeping** [comment]
Hey @Rayman-Sodhi , checkout  this https://github.com/ayush-sleeping/Clone-IT
Updated all the things, Which you recommended .

**Comment by Rayman-Sodhi** [comment]
great you can make a pr

**Comment by Rayman-Sodhi** [comment]
@ayush-sleeping  you have not taken the role as participant for Cloneit in excel sheet .
