### ISSUE TITLE
Telegram Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#402]
### Description

**Project title**
Telegram Website UI Clone

**Project Description**
This is the Clone of Telegram Website

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @SupriyaGembali
