### ISSUE TITLE
Fueler Website UI Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Rayman-Sodhi/Clone-IT#403]
### Description

**Project title**
Fueler Website UI Clone

**Description**
Fueler Creates Profiles

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @eswarbhageerath
