### ISSUE TITLE
Jet Brains Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#405]
### Description

**Project title**
Jetbrains Website UI Clone

**Description**
It will ensure that it always has a smooth and enjoyable experience when building and shipping your code planning and collaborating your work

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @SupriyaGembali

**Comment by whiteHatpro** [comment]
@SupriyaGembali update?

**Comment by SupriyaGembali** [comment]
@whiteHatpro Please review my PR
