### ISSUE TITLE
HackerEarth Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#406]
### Description

Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Clone Of Hacker Earth Website

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @SupriyaGembali
