### ISSUE TITLE
Leetcode Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Rayman-Sodhi/Clone-IT#407]
### Description

**Project title**
LeetCode Website Clone

**Description**
LeetCode is the best platform to help you enhance your skills, expand your knowledge and prepare for technical interviews.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @SupriyaGembali

**Comment by Rayman-Sodhi** [comment]
hey, @SupriyaGembali  this website clone has been found to be under plagiarised content by the team.If you  have any proof of it being genuine kindly share the proof ,otherwise this will be labeled invalid

**Comment by whiteHatpro** [comment]
@SupriyaGembali please give the update or we'll close the issue

**Comment by gurjeetsinghvirdee** [comment]
@whiteHatpro already merged

**Comment by whiteHatpro** [comment]
@gurjeetsinghvirdee this issue was the not closed so i didn't get it right
