### ISSUE TITLE
Groww investement website clone .

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Rayman-Sodhi/Clone-IT#409]
### Description
Hii I'm a GSSoc22 contributor and I want to add this clone of the investing website Groww. Clone of the homepage of Medium website using HTML and CSS. CLone of the below-given website. 

### Screenshot
![Screenshot (143)](https://user-images.githubusercontent.com/73521123/164934522-b05b3367-0b82-4631-8015-0668cac95427.png)
![Screenshot (144)](https://user-images.githubusercontent.com/73521123/164934526-cbad608c-8940-46c4-ac41-1d4c8f701dbb.png)

**Comment by Kumar-Ankit56** [comment]
[GSSoc22](url)

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Kumar-Ankit56

**Comment by whiteHatpro** [comment]
@Kumar-Ankit56 update?

**Comment by Kumar-Ankit56** [comment]
@whiteHatpro yeah it's on the way plz allow me some day I will soon create a PRs for this issue.
