### ISSUE TITLE
correct offer section  and categories section  in kfc clone

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#43]

**Comment by jalauk** [comment]
I would like to work on this issue

**Comment by Rayman-Sodhi** [comment]
<img width="960" alt="1" src="https://user-images.githubusercontent.com/65675692/150689449-5b723620-3206-48c3-b50e-1827291ed321.PNG">
<img width="959" alt="2" src="https://user-images.githubusercontent.com/65675692/150689455-74575774-992e-4d0f-96a8-f870134ead74.PNG">
<img width="943" alt="3" src="https://user-images.githubusercontent.com/65675692/150689459-91cf853d-a872-4f2d-8585-bd4a8cc53d5a.PNG">

**Comment by Rayman-Sodhi** [comment]
try to create same like main website...Offers should have a sliding carousel
