### ISSUE TITLE
Add all clones in the Readme file in the available clones section .

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#445]
Arrange all the clones alphabetically with proper links . This image shows the table where all clones have to be added
![Screenshot 2022-05-08 002515](https://user-images.githubusercontent.com/65675692/167268110-d1394487-fe35-4a6f-b4ae-f32bcb5027f7.png)

**Comment by gurjeetsinghvirdee** [comment]
> Arrange all the clones alphabetically with proper links . This image shows the table where all clones have to be added ![Screenshot 2022-05-08 002515](https://user-images.githubusercontent.com/65675692/167268110-d1394487-fe35-4a6f-b4ae-f32bcb5027f7.png)

Me ek baat bolu sabse faaltu kaam h ye badges ke sath README update krna🤣

**Comment by Rayman-Sodhi** [comment]
> > Arrange all the clones alphabetically with proper links . This image shows the table where all clones have to be added ![Screenshot 2022-05-08 002515](https://user-images.githubusercontent.com/65675692/167268110-d1394487-fe35-4a6f-b4ae-f32bcb5027f7.png)
> 
> Me ek baat bolu sabse faaltu kaam h ye badges ke sath README update krna🤣

haha koi nee order rhega about all clones

**Comment by gurjeetsinghvirdee** [comment]
@aaryahjolia kro kr diya assign
