### ISSUE TITLE
Add linktree clone in website maintain the 4 projects in one row

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#45]

**Comment by harshita214** [comment]
Can you explain this issue more

**Comment by Rayman-Sodhi** [comment]
if u check the webiste there are 4 projects in first column ,same way second column should have 4 projects too,currently it has 3 projects

**Comment by Rayman-Sodhi** [comment]
and please make a new pr  for linktree clone code after git pull

**Comment by tusharjain365** [comment]
hi, I would like to resolve this issue.

**Comment by Rayman-Sodhi** [comment]
@tusharjain365 sure go ahead .also if u can please change the title of linktee by making changes in index

**Comment by tusharjain365** [comment]
Sure, I will.
