### ISSUE TITLE
Add AMAZON clone

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#46]

**Comment by thisisharsh7** [comment]
Hi ma'am,
 I am a GSSoC'2022 participant and I want to work on this issue.
but Will you please describe it  little more ?

**Comment by MonarchGitHub** [comment]
I'd like to work on the Amazon clone, I plan to build it using **HTML, CSS ( I'd like to use Tailwind if you allow), and React JS**. 
My projected timeline is till **5th March**, I am confident that I can complete the Amazon clone by then.

**Comment by Rayman-Sodhi** [comment]
Hi @MonarchGitHub  you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .

**Comment by Rayman-Sodhi** [comment]
> Hi ma'am, I am a GSSoC'2022 participant and I want to work on this issue. but Will you please describe it little more ?

hey you can work on other beginner friendly issues or create some of your own

**Comment by gurjeetsinghvirdee** [comment]
the deadline passed so I'm removing u from this project @MonarchGitHub

**Comment by Kumar-laxmi** [comment]
Assign this issue to me

**Comment by Kumar-laxmi** [comment]
@gurjeetsinghvirdee Bro can you merge my recent pull request, so that I start working on this
