### ISSUE TITLE
PayPal Clone

### ISSUE THREAD

**Issue by Sukriti-m** [Rayman-Sodhi/Clone-IT#467]
### Description

I want to create a PayPal HomePage Clone using the following tech stack:

HTML

CSS

ReactJS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee Since no PR was made till now. Can you assign this to me

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @hariketsheth

**Comment by mdnazisharman2803** [comment]
@gurjeetsinghvirdee  can i work on this issue???

**Comment by gurjeetsinghvirdee** [comment]
Yeah u can @mdnazisharman2803
