### ISSUE TITLE
Geeks For Geeks Clone 

### ISSUE THREAD

**Issue by DragonUncaged** [Rayman-Sodhi/Clone-IT#475]
### Description

A coding Website Geek For Geek Clone

- [x] html

- [ ]  css

- [x]  js 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @DragonUncaged
