### ISSUE TITLE
Add hotstar clone

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#48]

**Comment by 1ananya3** [comment]
I want to work on this.Can you please assign it to me? I am a participant of GSSOC'22.

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue. I have already made a Netflix clone so working on this project is going to be interesting.

**Comment by Girlwithasmile** [comment]
Hello, if this issue is still open and not assigned to anyone, I would like to work on it. I am a contributer at gssoc'22 and have good frontend skills. I've previously worked on making netflix clone, linkedIn clone or other sites. Attaching a pic for reference.
![I've cloned netflix](https://user-images.githubusercontent.com/98261167/156113383-23740f97-87dc-424d-af25-41e1ddc02a51.png)

**Comment by Rayman-Sodhi** [comment]
> Hello, if this issue is still open and not assigned to anyone, I would like to work on it. I am a contributer at gssoc'22 and have good frontend skills. I've previously worked on making netflix clone, linkedIn clone or other sites. Attaching a pic for reference. ![I've cloned netflix](https://user-images.githubusercontent.com/98261167/156113383-23740f97-87dc-424d-af25-41e1ddc02a51.png)
you can add these changes in already existing netflix clone .Only if ur clone has more features

**Comment by artimanputra** [comment]
I would like to work on this issue. Can you assign it to me if someone is not working on it already?

**Comment by gurjeetsinghvirdee** [comment]
hey, @1ananya3 sorry but your time was up

**Comment by gurjeetsinghvirdee** [comment]
@Kushal-2002 assigning you and you have 6 days to complete either this issue goes to @Girlwithasmile

**Comment by gurjeetsinghvirdee** [comment]
@Girlwithasmile assigned to you? Reply if you active or complete this in a week

**Comment by Girlwithasmile** [comment]
Sure

**Comment by Girlwithasmile** [comment]
> Sure

Pls give me a little more time as I am in a hackathon. I've already completed many things and shall complete remaining soon!
![Screenshot 2022-03-22 100945](https://user-images.githubusercontent.com/98261167/159409694-3ebfa533-f9db-4f21-9bf8-c400fcc17f2c.png)

**Comment by gurjeetsinghvirdee** [comment]
> > Sure
> 
> Pls give me a little more time as I am in a hackathon. I've already completed many things and shall complete remaining soon!
> ![Screenshot 2022-03-22 100945](https://user-images.githubusercontent.com/98261167/159409694-3ebfa533-f9db-4f21-9bf8-c400fcc17f2c.png)
> 

Ok

**Comment by gurjeetsinghvirdee** [comment]
@Girlwithasmile are you working on it?

**Comment by gurjeetsinghvirdee** [comment]
No response from contributor so I'm closing this issue
