### ISSUE TITLE
Add Website Clones 

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#5]
Add famous websites clone by creating a new issue, we will assign you then you start working on your clones

**Comment by ayush-sleeping** [comment]
Hey @Rayman-Sodhi , 
In coming days I want to add a  "  NETFLIX  "  website clone .
What do you think about this , Let me know ..................

**Comment by anugoyal998** [comment]
Hey @Rayman-Sodhi 
I would like to add a " Disney+ Hotstart " clone both backend and frontend.

**Comment by Rayman-Sodhi** [comment]
@anugoyal998  you can start working on it ,but I will add the labels and then assign you . Most probably by 11 the scoring system will work

**Comment by anugoyal998** [comment]
> @anugoyal998  you can start working on it ,but I will add the labels and then assign you . Most probably by 11 the scoring system will work

Ok

**Comment by Rayman-Sodhi** [comment]
@anugoyal998   you can add your role in the excel sheet and start working on this issue

**Comment by anugoyal998** [comment]
> @anugoyal998 you can add your role in the excel sheet and start working on this issue

which excel sheet?

**Comment by Rayman-Sodhi** [comment]
check in discord

**Comment by VikasYadav-1** [comment]
@Rayman-Sodhi i am interested in creating Zomato website clone

**Comment by Rayman-Sodhi** [comment]
@VikasYadav-1  Make sure to add project id with your name  in excel sheet

**Comment by harshita214** [comment]
Hey I am interested in making a clone of Linktree

**Comment by Rayman-Sodhi** [comment]
@harshita214  Make sure to add project id with your name in excel sheet and start working

**Comment by harshit995** [comment]
@anugoyal998 i want to make hulu clone project... pls assign me

**Comment by anugoyal998** [comment]
> @anugoyal998 i want to make hulu clone project... pls assign me

Sorry, I'm not the project admin

**Comment by Rayman-Sodhi** [comment]
> @Rayman-Sodhi i am interested in creating Zomato website clone

u haven't added it yet.

**Comment by Ajoe12** [comment]
I am GSSOC-22 contributor I am interested to a contribute google keep clone, please assign me

**Comment by Rayman-Sodhi** [comment]
hey u can start once contribution peroid starts.  Also which clone you want to add

**Comment by bosedipayan** [comment]
Hey @Rayman-Sodhi , I'm a participant of GSsOC '22. I am interested in making a clone of inshorts(news) app.

**Comment by sakshi0210** [comment]
Hello @Rayman-Sodhi 
Can I make google classroom's website clone?
can you please assign me for this task?

**Comment by Rayman-Sodhi** [comment]
Hi  @Ajoe12  and @sakshi0210  you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days

**Comment by gurjeetsinghvirdee** [comment]
@sakshi0210 are you still working on issues?

**Comment by sakshi0210** [comment]
Yes

**Comment by gurjeetsinghvirdee** [comment]
@sakshi0210 then plz make a new issue, I wamt to know what are you working , I can't  add label here because this place foe discussion 

Make a new issue

**Comment by sakshi0210** [comment]
Okay 👍🏻

**Comment by GNtrazios** [comment]
Hey, I am interested in making a clone of a website. I was thinking about pizza fan (https://www.pizzafan.gr/en). Could u please assign me?

**Comment by gurjeetsinghvirdee** [comment]
@GNtrazios make a new issue plz then I will assign you
