### ISSUE TITLE
[New Issue]:  iPhone 13 Commercial Website clone

### ISSUE THREAD

**Issue by RAHULBAWA777** [Rayman-Sodhi/Clone-IT#538]
### Description

stack - HTML CSS JS

Fully Responsive With DARK AND LIGHT theme enabler

SS- 
![image](https://user-images.githubusercontent.com/91609324/169567823-68afa9e4-5e0c-4342-9527-1e859459d7ef.png)

https://user-images.githubusercontent.com/91609324/169568213-3de77899-7416-43e2-a5e0-fdcc03481289.mp4

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by RAHULBAWA777** [comment]
@gurjeetsinghvirdee ye bhi krdena ..... video will be in pr

**Comment by gurjeetsinghvirdee** [comment]
#52
