### ISSUE TITLE
Incorrect spacing in readme file 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Rayman-Sodhi/Clone-IT#54]
Hey , Greeting's of the day .. 
Ur readme file look's good but there is so many  extra space used , which make's it grammatically incorrect ..

Please assign this issue to me so i can change this and make grammatically correct ...
under **GSSOC'22
**
Thank's.. :crossed_fingers:

**Comment by gurjeetsinghvirdee** [comment]
> Hey , Greeting's of the day .. Ur readme file look's good but there is so many extra space used , which make's it grammatically incorrect ..
> 
> Please assign this issue to me so i can change this and make grammatically correct ... under **GSSOC'22 ** Thank's.. 🤞

That's not a valuable issue, I'm closing this even your grammar was wrong on that message
