### ISSUE TITLE
Add  YouTube Clone

### ISSUE THREAD

**Issue by anveshajain19** [Rayman-Sodhi/Clone-IT#55]
I want to work on this. Can you please assign it to me? I am a participant of GSSOC'22.
Thank you.

**Comment by biswajit150803** [comment]
I want to work on this issue under GSSoC 22.I have made clones of various apps previously so I would contribute well enough.

**Comment by Rayman-Sodhi** [comment]
Hi @biswajit150803  you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days

**Comment by gurjeetsinghvirdee** [comment]
> Hi  @anveshajain19  you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
> Deadline -  5-6 days
> after that it will be assigned to @biswajit150803
> 

Hey, I assigned @biswajit150803 because @anveshajain19 didn't complete yet and not replying in PR
