### ISSUE TITLE
AMAZON-CLONE

### ISSUE THREAD

**Issue by Dharmesh177** [Rayman-Sodhi/Clone-IT#553]
### Description

I have made a clone of amazon with mern stack and firebase. For everyone who wants to learn to react framework, it will be more useful for them.

Technology used:
React 
Redux
Firebase Authentication
Nodejs
Express Js
Firebase cloud

It is deployed on the firebase web server live.
URL:  https://clone-16e61.web.app/

We developed a FULL Amazon website with FULL E-Commerce Functionality using React-JS, Node-js, express, and firebase.
Implemented
Accounts and Login Page authenticate using firebase
Products Page
Cart and Checkout Page
Real Payments using stripe
Order History Page

![image](https://user-images.githubusercontent.com/77879603/169680201-5c72c284-bf23-4b63-b618-1d471b0a8012.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by Dharmesh177** [comment]
@Rayman-Sodhi assign this issue so that i can start contributing to it.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Dharmesh177

**Comment by Dharmesh177** [comment]
i am getting this error can you help to sort it out ASAP
![image](https://user-images.githubusercontent.com/77879603/170040774-b678d348-592c-485d-97dd-6db1c7e60ccb.png)

**Comment by gurjeetsinghvirdee** [comment]
> i am getting this error can you help to sort it out ASAP
> ![image](https://user-images.githubusercontent.com/77879603/170040774-b678d348-592c-485d-97dd-6db1c7e60ccb.png)
> 

I think you cloned orignal repo, 
You have to fork the orignal repo then make a clone of forked repo
