### ISSUE TITLE
Add Instagram Clone

### ISSUE THREAD

**Issue by anveshajain19** [Rayman-Sodhi/Clone-IT#56]
@Rayman-Sodhi 
I want to work on this. This will help me to enhance my skills. Can you please assign it to me? I am a participant of GSSOC'22.
Thank you.

**Comment by biswajit150803** [comment]
I want to work on this issue under GSSoC 22.I have already made clones of various apps and so I could contribute well enough

**Comment by Prajwal-ctrl** [comment]
hey @abhi1e9-1e10  I am a gssoc'22 participant can work on it . I made twitter clone already

**Comment by Anish1411** [comment]
hey , i want to work on this issue , plz assign it to me

**Comment by Rayman-Sodhi** [comment]
Hi  @anveshajain19  you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days
after that it will be assigned to @biswajit150803

**Comment by anveshajain19** [comment]
Thank you @Rayman-Sodhi for assigning it to me..
