### ISSUE TITLE
Add WhatsApp Clone

### ISSUE THREAD

**Issue by abhi1e9-1e10** [Rayman-Sodhi/Clone-IT#57]

**Comment by biswajit150803** [comment]
I have already made clones of various apps and so I could contribute well enough

**Comment by Prajwal-ctrl** [comment]
hey @abhi1e9-1e10  I am a gssoc'22 participant can work on it . i made twitter clone already

**Comment by lokita282** [comment]
Hi I am a gssoc '22 participant and would like to work on this issue. I am already working on making a real time chat appliation so...
