### ISSUE TITLE
youtube clone

### ISSUE THREAD

**Issue by Dharmesh177** [Rayman-Sodhi/Clone-IT#573]
### Description

I have implemented a youtube clone using HTML CSS and javascript.

 It is 95% the same as youtube. I included a banner, a movable menu button, and some videos. 
you can watch videos, comment, and subscribe .
There is an expandable description and a comment section.
 it is also responsive to mobile screens.

![preview2](https://user-images.githubusercontent.com/77879603/170205121-32531fbd-639b-4570-8b09-2e059b89a564.png)
![pewview3](https://user-images.githubusercontent.com/77879603/170205151-9b81e0cb-4aaf-4be2-b6c7-45751b897b4f.png)
![preview1](https://user-images.githubusercontent.com/77879603/170205174-4bf262b0-b299-4de0-843a-544c4833c84a.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by Dharmesh177** [comment]
Hey menters assign this issue to me so that i can contribute. @Rayman-Sodhi @gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Dharmesh177
