### ISSUE TITLE
TinDog (Tinder for Dogs)

### ISSUE THREAD

**Issue by piyusha2001** [Rayman-Sodhi/Clone-IT#578]
### Description

This would be something different . I can make frontend for it using HTML,CSS and Bootstrap.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
ok make this
