### ISSUE TITLE
Confirmed password not hidden

### ISSUE THREAD

**Issue by Girlwithasmile** [Rayman-Sodhi/Clone-IT#58]
In the signup page in netflix clone, When I type the password it is replaced by dots as usual but when I confirm it it is not. I would like to work on this issue. I am a contributer at gssoc'22.
![Screenshot 2022-02-28 222841_LI](https://user-images.githubusercontent.com/98261167/156027139-82bc7987-072b-4e1c-863f-774ae982a486.jpg)

**Comment by gurjeetsinghvirdee** [comment]
you can work on this issue @Girlwithasmile & Add a video on your PR so we can see your code works or not

**Comment by gurjeetsinghvirdee** [comment]
@Girlwithasmile your hackathon completed? And you are free to complete this issue or I will close it?

**Comment by gurjeetsinghvirdee** [comment]
Closing this issue bcoz no response from the contributor side
