### ISSUE TITLE
Netflix Clone

### ISSUE THREAD

**Issue by Dharmesh177** [Rayman-Sodhi/Clone-IT#588]
### Description

Netflix clone using HTML, CSS, and Javascript.

it has many features like login, header, footer, the main body of Netflix clone, various movie crime show tv shows, etc.

![preview5](https://user-images.githubusercontent.com/77879603/170416375-48012b9f-caef-40f6-8ab5-7e54b59a2eeb.png)
![preview4](https://user-images.githubusercontent.com/77879603/170416396-69eecfb1-8cdc-49ec-8d3a-1ba775c59a82.png)
![preview3](https://user-images.githubusercontent.com/77879603/170416417-9e7ec0d9-edca-4f7b-907f-1e15e8b27665.png)
![preview2](https://user-images.githubusercontent.com/77879603/170416464-005fcc74-96be-4c88-98e0-3165b121c3cb.png)
![preview1](https://user-images.githubusercontent.com/77879603/170416505-c6f5becf-d875-43ce-812b-b70005799b85.png)
![6](https://user-images.githubusercontent.com/77879603/170416527-c40b1c66-bf10-4c7a-b66c-eb830e355dda.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by Dharmesh177** [comment]
hey, @Rayman-Sodhi @gurjeetsinghvirdee assign so that I can contribute as it is built from core web technology HTML CSS js it helps many peoples to learn that stuff.

**Comment by gurjeetsinghvirdee** [comment]
Netflix already there you can check on readme list or deployed link 
Make something new @Dharmesh177
