### ISSUE TITLE
Add Starbucks clone

### ISSUE THREAD

**Issue by Girlwithasmile** [Rayman-Sodhi/Clone-IT#59]
I am a contributer at gssoc'22 and would like to make a ui clone of everyone's favourite Starbucks. I would be glad if u assign this issue to me.I would love to work on this. @Rayman-Sodhi 
I've previously made a netflix clone too
![I've cloned netflix](https://user-images.githubusercontent.com/98261167/156113126-5935d736-f013-451f-8526-c1ec2486a9b4.png)

**Comment by sagnik2001** [comment]
Can I work on this under GSSoC 22

**Comment by Girlwithasmile** [comment]
> Can I work on this under GSSoC 22

Actually I opened this cause I wanna work for this.

**Comment by gurjeetsinghvirdee** [comment]
Closes #100
