### ISSUE TITLE
Twitch Clone using React

### ISSUE THREAD

**Issue by shrey2003** [Rayman-Sodhi/Clone-IT#590]
### Description

I want to make a twitch clone using HTML, CSS, ReactJs

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by shrey2003** [comment]
@gurjeetsinghvirdee please assign me this issue

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @shrey2003
