### ISSUE TITLE
'My Profile' page on LinkedIn Clone

### ISSUE THREAD

**Issue by Sanjanabharadwaj25** [Rayman-Sodhi/Clone-IT#6]

**Comment by Sanjanabharadwaj25** [comment]
The clone can be enhanced by including my profile section that contains the data of the user. 
Selected data can also be viewed by other users.

**Comment by Sanjanabharadwaj25** [comment]
I would like to work on this issue.

**Comment by Rayman-Sodhi** [comment]
Hi, I will assign you this one as soon as I add the labels.

**Comment by Rayman-Sodhi** [comment]
Hi @Sanjanabharadwaj25  you can work on this issue .It would be great if you try using bootstrap as the clone is made in bootstrap

**Comment by Sanjanabharadwaj25** [comment]
Sure, I will use bootstrap for this.
