### ISSUE TITLE
Add Google Search Engine Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Rayman-Sodhi/Clone-IT#60]
I'm a GSSo'C 22 contributor, I love this cloning project & I want to add Google Search Engine Clone with React Js using google API, Please assign me this issue, So I will work on it

![Screenshot (672)](https://user-images.githubusercontent.com/73753957/156113141-3caa0dd8-6472-4221-b917-eff7f884db7d.png)

**Comment by sagnik2001** [comment]
Can I work on this under GSSoC 22

**Comment by thisisharsh7** [comment]
I too want to work on this issue @Rayman-Sodhi will you please assign it to me

**Comment by Rayman-Sodhi** [comment]
Hi  @gurjeetsinghvirdee     you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days

**Comment by gurjeetsinghvirdee** [comment]
Ok sure I will complete in 2-3 days 🧡

**Comment by sampavaranasi** [comment]
@Rayman-Sodhi https://github.com/khushi-purwar/WebDev-ProjectKart/issues/403
