### ISSUE TITLE
Skeleton Effect Guide

### ISSUE THREAD

**Issue by Dharmesh177** [Rayman-Sodhi/Clone-IT#603]
### Is your feature request related to a problem? Please describe.

I saw almost every clone of this repo it seems like very less people applied the skeleton effect to their project.

### Describe the solution you'd like.

using skeleton we can attract more users because before our data is loaded it will show a temporary template.
hence I created a skeleton effect template using react js and I fetched data from random data API (await API).

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/77879603/170652899-baa03d8b-3bd4-4b43-820a-e5c5e6fbf4f3.png)
![image](https://user-images.githubusercontent.com/77879603/170652952-7931ed8f-4f1f-4601-8016-90cb0d946612.png)
![image](https://user-images.githubusercontent.com/77879603/170653034-65fc24f4-08a7-49b4-babd-14372e0e66ee.png)

**Comment by Dharmesh177** [comment]
assign this to me @gurjeetsinghvirdee @Rayman-Sodhi

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Dharmesh177 
Please deploy your project also
