### ISSUE TITLE
Add Ola Clone

### ISSUE THREAD

**Issue by sagnik2001** [Rayman-Sodhi/Clone-IT#61]
I am a GSsoc 2022 contributor and I want to make a ola clone

**Comment by Rayman-Sodhi** [comment]
Hi @sagnik2001     you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days

**Comment by gurjeetsinghvirdee** [comment]
hey @sagnik2001 you crossed your timeline! still, working on this?

**Comment by sagnik2001** [comment]
Hey @gurjeetsinghvirdee, sorry I need to unassign myself as I don't have enough time to complete this also the deadline has passed

**Comment by gurjeetsinghvirdee** [comment]
> Hey @gurjeetsinghvirdee, sorry I need to unassign myself as I don't have enough time to complete this also the deadline has passed

Then closing this issue
