### ISSUE TITLE
Add Tinder Clone 

### ISSUE THREAD

**Issue by sagnik2001** [Rayman-Sodhi/Clone-IT#63]
I am a GSsoc 2022 contributor and will like to clone Tinder

**Comment by Anish1411** [comment]
hey , i want to work on this , plz assign it to me

**Comment by neetra** [comment]
hey I would like to work on this project

**Comment by Rayman-Sodhi** [comment]
Hi @sagnik2001     you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days
after that it will be assigned to @Anish1411

**Comment by gurjeetsinghvirdee** [comment]
hey, @sagnik2001 you crossed the deadline date now this issue is assigned to @Anish1411

**Comment by gurjeetsinghvirdee** [comment]
@Anish1411 you have 6 days to complete

**Comment by Anish1411** [comment]
hey @gurjeetsinghvirdee , can u plz tell me i have to clone only login page or i have to clone the interface that comes after login.
if possible , send me ss , what actually i have to build

**Comment by gurjeetsinghvirdee** [comment]
You have to build login with interface

**Comment by Anish1411** [comment]
can u plz send me screen shots

**Comment by gurjeetsinghvirdee** [comment]
> can u plz send me screen shots

@Anish1411 you commented on this issue that you want to work on, the last person who worked on this issue didn't create any PR so I can't have ss something, so built on your own idea that's your choice you want to make a design or in add some functions, if you can then reply either I have to assign @neetra

**Comment by Anish1411** [comment]
okk , i'll

**Comment by gurjeetsinghvirdee** [comment]
> okk , i'll

then start your work

**Comment by gurjeetsinghvirdee** [comment]
@Anish1411 are you still working with this?

**Comment by Anish1411** [comment]
yeah i will submit it by tomorrow

**Comment by gurjeetsinghvirdee** [comment]
Ok
