### ISSUE TITLE
Improving Website Animations

### ISSUE THREAD

**Issue by XZANATOL** [Rayman-Sodhi/Clone-IT#64]
## Issue

The website has a stylish theme but with rigid animations as shown in this GIF:

![Peek 2022-03-01 02-21](https://user-images.githubusercontent.com/64689436/156081104-646dceb6-2dea-42fe-b6f2-fdcb6ed29370.gif)

The animation is rigid **on leaving hover** state.

## Idea

I can improve the user experience and smooth the animation to look something like this:

![Peek 2022-03-01 02-25](https://user-images.githubusercontent.com/64689436/156081422-6c2e6937-7509-4cd7-899e-89720b811959.gif)

## Subject

Issue created under GSSOC'22 contributions.

**Comment by Rayman-Sodhi** [comment]
Hi @XZANATOL    you can work on this issue .You can try to make the changes soon as new clones will be added from time to time.

**Comment by XZANATOL** [comment]
@Rayman-Sodhi The changes are ready.
