### ISSUE TITLE
Improve  the project section UI

### ISSUE THREAD

**Issue by kheya19** [Rayman-Sodhi/Clone-IT#65]
I can make it look clean for a better feel and user experience. Assign  me this task as I m a GSSOC'22 contributor

**Comment by Rayman-Sodhi** [comment]
hi I will assign this after issue #64 is closed

**Comment by kheya19** [comment]
> hi I will assign this after issue #64 is closed

Ok thank you 😊

**Comment by Rayman-Sodhi** [comment]
Hi @XZANATOL you can work on this issue  and also add Facebook clone to the project section ,the link can be found in project readme.
Deadline - 5-6 days

**Comment by kheya19** [comment]
> Hi  @kheya19 you can work on this issue  
> Deadline - 5-6 days
> 
> 

Ok thank you

**Comment by gurjeetsinghvirdee** [comment]
#120 merged
