### ISSUE TITLE
Creating issue Forms for the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [Rayman-Sodhi/Clone-IT#68]
I want to add a few issue Forms so that it will be convenient for new contributors to open issues. I plan to create  **Bug Report** and **Feature Request** Forms. You can read more about issue forms [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**
- **Urgency indicator**
- **Desktop Info (OS, Version, Browser etc):**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Timeline- I can complete this task by 3 March**

**Comment by Rayman-Sodhi** [comment]
Great ! but before making a pr please show me the ss or demo if its working properly .
You can take 5-6 days

**Comment by MonarchGitHub** [comment]
Yes sure, I will attach preview links.

**Comment by MonarchGitHub** [comment]
Hello @Rayman-Sodhi , I have added **bug report** and **feature request** issue forms to the repo.
I have also attached the previews of the issue forms below. Kindly review the changes and inform if I should create a PR.

**_Previews_**

- [Bug Report](https://github.com/MonarchGitHub/Clone-IT/blob/issueform/.github/ISSUE_TEMPLATE/Bug_report.yaml)

- [Feature Request](https://github.com/MonarchGitHub/Clone-IT/blob/issueform/.github/ISSUE_TEMPLATE/feature_request.yaml)

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi please check this

**Comment by Rayman-Sodhi** [comment]
hi  @monarchGithub You can make a pr after pulling the changes

**Comment by MonarchGitHub** [comment]
Okay got it 👍
