### ISSUE TITLE
Add Facebook Clone

### ISSUE THREAD

**Issue by Vaib215** [Rayman-Sodhi/Clone-IT#69]
I can add facebook clone made using html and tailwind css. I am participant of GS-SOC 2022. Please allow me.

**Comment by Rayman-Sodhi** [comment]
Hi @Vaib215    you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days

**Comment by Vaib215** [comment]
I have created the clone. Kindly merge the PR.
