### ISSUE TITLE
Paytm Clone

### ISSUE THREAD

**Issue by SumitKanth** [Rayman-Sodhi/Clone-IT#693]
### Description

I will make paytm clone

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @SumitKanth 
Add Deployed link also in your project folder

**Comment by SumitKanth** [comment]
okk

**Comment by gurjeetsinghvirdee** [comment]
#694
