### ISSUE TITLE
Zomato Clone

### ISSUE THREAD

**Issue by Akanksha-Sen** [Rayman-Sodhi/Clone-IT#696]
### Description

Zomato Landing Page

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
make something else, zomato is already there! You can check here https://rayman-sodhi.github.io/Clone-IT/

**Comment by gurjeetsinghvirdee** [comment]
You can make different of website clones like
Perfume related sites
watch 
clothing brands

**Comment by Akanksha-Sen** [comment]
I've cloned zomato landing page which is pretty much different from the one already uploaded on the repo. I can also clone anything else if you say but I'll need some time for it.

**Comment by gurjeetsinghvirdee** [comment]
> I've cloned zomato landing page which is pretty much different from the one already uploaded on the repo. I can also clone anything else if you say but I'll need some time for it.

Ok if your clone better than existing project tjen go for it
