### ISSUE TITLE
SB UI KIT PRO Lead-Capture Clone

### ISSUE THREAD

**Issue by khushimarothi** [Rayman-Sodhi/Clone-IT#698]
### Description

I want to create the clone of SB UI KIT PRO lead capture page. This page will use bootstrap,  css and a color customizer designed by Javascript. 

Kindly assign it to me.

Here is the page link.
https://sb-ui-kit-pro-angular.startbootstrap.com/landings/lead-capture

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @khushimarothi

**Comment by khushimarothi** [comment]
Thanks!!
