### ISSUE TITLE
Fixing navigation bar of the KFC clone.

### ISSUE THREAD

**Issue by arpita221b** [Rayman-Sodhi/Clone-IT#7]
![Screenshot (1148)](https://user-images.githubusercontent.com/56889637/144753013-72bb1cf8-3093-4dc2-8669-ba902934118c.png)
For now, this is what the navigation bar of the actual website looks like and I would like to implement the same in the clone. 
Please review my issue.

**Comment by Rayman-Sodhi** [comment]
Hi, I will assign you this one as soon as I add the labels.

**Comment by Rayman-Sodhi** [comment]
Hi @arpita221b  you can add your role in the excel sheet and start working on this issue

**Comment by arpita221b** [comment]
Okay Sure!
