### ISSUE TITLE
Add Discord Clone

### ISSUE THREAD

**Issue by Rajdip019** [Rayman-Sodhi/Clone-IT#70]
Here is a link:  https://discord-clone-rajdeep019.vercel.app/dashboard

**Comment by Rayman-Sodhi** [comment]
Hi @Rajdip019      you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days

**Comment by gurjeetsinghvirdee** [comment]
@Rajdip019 deadline passed and someone already make a discord clone, So I'm closing this issue
