### ISSUE TITLE
Cartoon Network Website clone

### ISSUE THREAD

**Issue by khushimarothi** [Rayman-Sodhi/Clone-IT#702]
### Description

I want to add the clone of cartoon network website. Tech used: html, css.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @khushimarothi
