### ISSUE TITLE
Fackbook Login Page

### ISSUE THREAD

**Issue by SumitKanth** [Rayman-Sodhi/Clone-IT#706]
### Description

I will add face book login page UI.

I will contribute under HSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

**Comment by gurjeetsinghvirdee** [comment]
I'm closing this issue 
As we already have the Facebook clone
Make something unique that is not part of this Repository

**Comment by SumitKanth** [comment]
I will make facebook login page which is not in your repoitory.

**Comment by gurjeetsinghvirdee** [comment]
Login page and clone not so different

**Comment by SumitKanth** [comment]
okii
