### ISSUE TITLE
Airbnb  Clone

### ISSUE THREAD

**Issue by Mrjoy832** [Rayman-Sodhi/Clone-IT#71]
Hi, I am TRIDIB BAG. I'm a GSSoC22 participant.
I want to add landing page clone of Airbnb with proper documentation as there is nothing regarding this . I'm really want to contribute in this topic .

Can @Rayman-Sodhi ,  please assign it to me?

**Comment by Rayman-Sodhi** [comment]
Hi @Mrjoy832     you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline -  5-6 days
after that it will be assigned to @Anish1411

**Comment by Mrjoy832** [comment]
Ok I will start as soon as possible

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 are you still working on this? how much time you want to finish because you already passed the deadline!
