### ISSUE TITLE
Airbnb clone related bugs

### ISSUE THREAD

**Issue by cybraia** [Rayman-Sodhi/Clone-IT#711]
### Back not working
After clicking on Airbnb icon, it doesn't take to the homepage. 
### The website is not responsive
After choosing a service, the web page is not mobile friendly.

### How can we reproduce this bug?

While clicking on the Airbnb icon, it should bring you to the home page.
The webpages need to be mobile responsive, the ratio of pictures to text is not correct. 
I can fix both issues. Please assign me the issue.

### Urgency (Optional)

None

**Comment by gurjeetsinghvirdee** [comment]
@cybraia assigned you!

**Comment by cybraia** [comment]
Hi, I tried working on it. The code doesn't contain the webpage linking. I didn't find the linked page, hence couldn't solve it. Could you check and let me know if the page exists and I missed it?

**Comment by gurjeetsinghvirdee** [comment]
> Hi, I tried working on it. The code doesn't contain the webpage linking. I didn't find the linked page, hence couldn't solve it. Could you check and let me know if the page exists and I missed it?

Hey, maybe now you can go with your issue, that's my mistake I reverted the dozen number of PRs at a time of **GSSoC** so it was deleted by mistake
