### ISSUE TITLE
Making the navbar responsive and improve UI of footer

### ISSUE THREAD

**Issue by iamtanya-22** [Rayman-Sodhi/Clone-IT#73]

**Comment by AnweshaRoses** [comment]
hello, I would like to work on this. Can you please assign this to me.

**Comment by iamtanya-22** [comment]
Hey , I want to work on this issue .
Please assign this issue to me under GSSOC'22

**Comment by Rayman-Sodhi** [comment]
hi I will assign this after issue #64 and #65  is closed

**Comment by AnweshaRoses** [comment]
sure thank you @Rayman-Sodhi

**Comment by Rayman-Sodhi** [comment]
Hi @iamtanya-22  you can work on this  issue
Deadline 5-6 days
After that it will be assigned to @AnweshaRoses

**Comment by iamtanya-22** [comment]
> Hi @iamtanya-22  you can work on this  issue
> Deadline 5-6 days
> After that it will be assigned to @AnweshaRoses 

Okay. I will finish this before deadline.

**Comment by gurjeetsinghvirdee** [comment]
> > Hi @iamtanya-22  you can work on this  issue
> > Deadline 5-6 days
> > After that it will be assigned to @AnweshaRoses
> 
> Okay. I will finish this before deadline.

hey, @iamtanya-22 are you still working on this issue?

**Comment by gurjeetsinghvirdee** [comment]
closing this issue coz of no response
