### ISSUE TITLE
Adding QUORA clone

### ISSUE THREAD

**Issue by Rhydham2809** [Rayman-Sodhi/Clone-IT#74]
I can beautifully add an Quora clone with my skills in HTML and CSS.
I am Gssoc 2022 participate.
Kindly assign this issue to me.

**Comment by Rayman-Sodhi** [comment]
Hi @Rhydham2809   you can work on this issue ur project should have a working link and you should add that in the main website too once done with creating it .
Deadline - 5-6 days

**Comment by Rhydham2809** [comment]
Thank you for assigning me this issue, I will do my best.

**Comment by gurjeetsinghvirdee** [comment]
> Thank you for assigning me this issue, I will do my best.

Hey, @Rhydham2809 Are you still working on this issue?

**Comment by Rhydham2809** [comment]
Hello,
Yes I am working on this issue and it is almost ready, shortly I will pull a merge request and sorry for such delay.
