### ISSUE TITLE
Netflix Clone

### ISSUE THREAD

**Issue by AnweshaRoses** [Rayman-Sodhi/Clone-IT#75]
Heyy I would like to work on this issue can you please assign this to me

**Comment by Rayman-Sodhi** [comment]
Hi @AnweshaRoses  there is already a netflix clone ..if your clone has more features then kindly mention them after cross checking from website

**Comment by gurjeetsinghvirdee** [comment]
Hey, @AnweshaRoses are you still want to work on this issue with extra features on the Netflix clone? Please reply either I will close this issue

**Comment by AnweshaRoses** [comment]
hey you can close this issue
