### ISSUE TITLE
Fixing the navigation bar of linkedIn clone

### ISSUE THREAD

**Issue by sanjana317** [Rayman-Sodhi/Clone-IT#8]
the navigation bar can be enhanced by adding more features  like  network and jobs

**Comment by sanjana317** [comment]
I would like to work on this issue

**Comment by Rayman-Sodhi** [comment]
Hi @sanjana317  you can add your role in the excel sheet and start working on this issue

**Comment by sanjana317** [comment]
Yes I will Thank you.
