### ISSUE TITLE
Add a Instagram Clone

### ISSUE THREAD

**Issue by Aritra777** [Rayman-Sodhi/Clone-IT#82]
I want to add an instagram clone to this website clone list. The clone site will look like this -
I am using HTML, CSS, JS, ReactJS to build this.
![Screenshot (33)](https://user-images.githubusercontent.com/93366359/156580029-04d0bdc0-761d-489a-92e1-090fc8f762cc.png)
Can you assign me under GSSOC'22.

**Comment by Rayman-Sodhi** [comment]
Already assigned #56
