### ISSUE TITLE
Add CODM S13 UI clone using HTML CSS only.

### ISSUE THREAD

**Issue by Debdeep1** [Rayman-Sodhi/Clone-IT#84]

**Comment by Debdeep1** [comment]
I want to work on this issue under GSSoC'22

**Comment by Rayman-Sodhi** [comment]
CODM S13 is this a website?

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi @Debdeep1 I'm closing this issue because of no response & CODM S13 was a call of duty game game not a website
