### ISSUE TITLE
New footer for the page

### ISSUE THREAD

**Issue by SushantPatial** [Rayman-Sodhi/Clone-IT#9]
I would like to replicate the footer for the KFC website.

![image](https://user-images.githubusercontent.com/84243683/145150771-d8bcbee7-02db-4ceb-a54f-01d89158b1f1.png)

**Comment by Rayman-Sodhi** [comment]
Great, you can start working on it . The scoring system will work from 11 most probably.Then I will assign u

**Comment by Rayman-Sodhi** [comment]
Hi  @SushantPatial  you can add your role in the excel sheet and start working on this issue
