### ISSUE TITLE
Add Google Clone

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Rayman-Sodhi/Clone-IT#91]
This website will made using html, css, js. Please assign me this Issue.

**Comment by whiteHatpro** [comment]
@Sulagna-Dutta-Roy can u explain your site a little bit more
what u want to achieve?

**Comment by Sulagna-Dutta-Roy** [comment]
My google clone website will be look like actual website: https://www.google.com
Do check here.

**Comment by mayank-del** [comment]
can I also work in it under GSSOC '22?

**Comment by Sulagna-Dutta-Roy** [comment]
> can I also work in it under GSSOC '22?

This is my reference of my project.

**Comment by mayank-del** [comment]
Can i also work in this project under GSSoC 22?
