### ISSUE TITLE
Add GitHub Clone

### ISSUE THREAD

**Issue by Adbnemesis** [Rayman-Sodhi/Clone-IT#94]
Since no one is working on adding the github clone, I can do the honors.
I'll first make the home page using html,css and js then adding authentication will come later

**Comment by Rayman-Sodhi** [comment]
it is already open #81 .If youn find some more featues to add then u can add it after I close #81

**Comment by Adbnemesis** [comment]
Since it wants to add only the home page, I can add the authentication to it? Will it work?

**Comment by gurjeetsinghvirdee** [comment]
> Since it wants to add only the home page, I can add the authentication to it? Will it work?

Let's finish him when project was merged in this repo you can work on that. I will assign you when it merged

**Comment by gurjeetsinghvirdee** [comment]
> Since it wants to add only the home page, I can add the authentication to it? Will it work?

@Adbnemesis are you willing to work with github homepage clone ? Let me know

**Comment by gurjeetsinghvirdee** [comment]
Closing this issue bcoz no response from contributor side

**Comment by Adbnemesis** [comment]
Yes I am willing to work with GitHub clone page. I'm sorry I was very busy with my exams and all

**Comment by gurjeetsinghvirdee** [comment]
> Yes I am willing to work with GitHub clone page. I'm sorry I was very busy with my exams and all

Make a new issue with clear description I will assign you
