### ISSUE TITLE
Add Search button for the Projects section

### ISSUE THREAD

**Issue by zugzwang03** [Rayman-Sodhi/Clone-IT#95]
I would like to add a search feature below the project header, where when the user will search a particular project and click on it, that particular project website will be redirected to the user. I would like to work on this issue under GSSOC'22, but I require 4 days time for it.

**Comment by gurjeetsinghvirdee** [comment]
> I would like to add a search feature below the project header, where when the user will search a particular project and click on it, that particular project website will be redirected to the user. I would like to work on this issue under GSSOC'22, but I require 4 days time for it.

@Rayman-Sodhi @whiteHatpro check it this issue

**Comment by whiteHatpro** [comment]
@zugzwang03 please explain your issue a little bit more

**Comment by zugzwang03** [comment]
![cloneIT](https://user-images.githubusercontent.com/95460021/158732017-c1406627-f35d-4979-9c12-55d9a9f492cc.png)
At the straight blue line area, I want to add a search button feature so that an user can type the required project there and get redirected to that particular project website. For example, typing Flipkart Clone and pressing enter will take the user to the Flipkart Clone website.

**Comment by gurjeetsinghvirdee** [comment]
> ![cloneIT](https://user-images.githubusercontent.com/95460021/158732017-c1406627-f35d-4979-9c12-55d9a9f492cc.png)
> At the straight blue line area, I want to add a search button feature so that an user can type the required project there and get redirected to that particular project website. For example, typing Flipkart Clone and pressing enter will take the user to the Flipkart Clone website.

Go ahead @zugzwang03
