### ISSUE TITLE
Adding Carousel Landing Page

### ISSUE THREAD

**Issue by XZANATOL** [Rayman-Sodhi/Clone-IT#99]
## Idea

Add a responsive landing page template based on customized bootstrap 5 carousel that is suitable for volunteering communities to showcase their activity along with their timeline of upcoming events.

## Tech stack

- [x] HTML
- [x] CSS
- [x] JS
- [x] Bootsrap 5

## Screenshot

![image](https://user-images.githubusercontent.com/64689436/156903213-f9fc50ea-9310-4d90-9844-b6f650694e6d.png)

Issue made under GSSoC'22 contributions

**Comment by Rayman-Sodhi** [comment]
sure you can work on this but please send  a ss before maki9ng a pr

**Comment by XZANATOL** [comment]
@Rayman-Sodhi sorry, you mean sending a a screenshot? inside the PR, Or where should I send it?

**Comment by XZANATOL** [comment]
@gurjeetsinghvirdee Ok Done.

https://user-images.githubusercontent.com/64689436/157394047-2263ec4f-a4b4-477b-85cd-59d1ce4f008f.mp4

**Comment by XZANATOL** [comment]
@gurjeetsinghvirdee shall I make a PR?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee shall I make a PR?

bro, I'm not a mentor, I just clear your doubt, what @Rayman-Sodhi want to say in the last comments, so tag her in discord or here

**Comment by XZANATOL** [comment]
Ah my bad, sorry for the miss-understanding xd
@Rayman-Sodhi shall I continue with the PR request?
